# Initially generated by GitHub Copilot.
"""Extract structured ChangeOps from a classified MAM-parsed-plus diff.

This module reimplements the *extraction* half of the logic formerly
interleaved with English rendering in describe_diff._describe_diff().
It imports infrastructure helpers from describe_diff and other existing
modules but does not modify them.

Exports:
    extract_change_ops — produce a list[ChangeOp] for one diff
"""

from collections import Counter
from difflib import SequenceMatcher

from mb_cmn.hebrew_punctuation import NU_GMAQ, PASOLEG
from mb_cmn.str_defs import DOUB_VERT_LINE
from mb_diff_mpu.change_ops import (
    ComplexReplace,
    GenericReplace,
    GenericTextReplace,
    GrayMaqafAdded,
    GrayMaqafRemoved,
    MarkAdded,
    MarkMoved,
    MarkRemoved,
    MarkReplaced,
    MarkReordered,
    PaseqAdded,
    PaseqRemoved,
    TemplateAdded,
    TemplateRemoved,
    TemplateRestructured,
)
from mb_diff_mpu.change_ops_apply import apply_text_ops
from mb_diff_mpu.describe_diff import (
    ACCENT_CATS,
    LEG_SENTINEL,
    MARK_CATS,
    NAR_SENTINEL,
    collect_paseq_types,
    has_paseq,
    is_accent,
    is_letter,
    is_mark,
    is_poetic,
    qualify,
)
from mb_diff_mpu.mpplus_structure import template_name_multiset_delta

# ── Mark / accent extraction ────────────────────────────────


def _extract_mark_ops(old_text, new_text, pred):
    """Extract ChangeOps for mark/accent differences.

    *pred* selects the character type (is_accent or is_mark).
    Returns a list of ChangeOps, or None if there are no differences.
    """
    old_letter_counts = Counter(ch for ch in old_text if is_letter(ch))
    new_letter_counts = Counter(ch for ch in new_text if is_letter(ch))
    # When the letter inventory changed, occurrence numbers shift and the
    # mark-level diff produces bogus MarkMoved ops.  Fall back.
    if old_letter_counts != new_letter_counts:
        return None
    old_qualified = qualify(old_text, pred)
    new_qualified = qualify(new_text, pred)

    # Pure reorder: same items in a different order on the same letter
    if (
        Counter(old_qualified) == Counter(new_qualified)
        and old_qualified != new_qualified
    ):
        start = 0
        while old_qualified[start] == new_qualified[start]:
            start += 1
        end = len(old_qualified) - 1
        while old_qualified[end] == new_qualified[end]:
            end -= 1
        region = old_qualified[start : end + 1]
        letters = {l for _, l, _ in region}
        if len(letters) == 1:
            chars = tuple(a for a, _, _ in region)
            _, letter, occ = region[0]
            return [MarkReordered(chars=chars, on_letter=letter, letter_occurrence=occ)]

    sm = SequenceMatcher(None, old_qualified, new_qualified, autojunk=False)
    opcodes = [op for op in sm.get_opcodes() if op[0] != "equal"]

    if not opcodes:
        return None

    deletes = []
    inserts = []
    ops = []

    for tag, i1, i2, j1, j2 in opcodes:
        old_chunk = old_qualified[i1:i2]
        new_chunk = new_qualified[j1:j2]

        if tag == "replace" and len(old_chunk) == 1 and len(new_chunk) == 1:
            o_mark, o_let, o_occ = old_chunk[0]
            n_mark, n_let, n_occ = new_chunk[0]
            if o_mark == n_mark:
                # Same mark, different letter → moved
                ops.append(
                    MarkMoved(
                        char=o_mark,
                        from_letter=o_let,
                        from_occurrence=o_occ,
                        to_letter=n_let,
                        to_occurrence=n_occ,
                    )
                )
            elif o_let == n_let and o_occ == n_occ:
                # Same letter, different mark → replaced
                ops.append(
                    MarkReplaced(
                        on_letter=o_let,
                        letter_occurrence=o_occ,
                        old_char=o_mark,
                        new_char=n_mark,
                    )
                )
            else:
                ops.append(
                    GenericReplace(
                        old_char=o_mark,
                        old_letter=o_let,
                        new_char=n_mark,
                        new_letter=n_let,
                    )
                )
        elif tag == "delete":
            for mark, let, occ in old_chunk:
                deletes.append((mark, let, occ))
        elif tag == "insert":
            for mark, let, occ in new_chunk:
                inserts.append((mark, let, occ))
        else:
            # Complex replace
            ops.append(
                ComplexReplace(
                    old_qualified=tuple(old_chunk),
                    new_qualified=tuple(new_chunk),
                )
            )

    # Pair delete/insert of same mark as moves
    used_inserts = set()
    for d_mark, d_let, d_occ in deletes:
        paired = False
        for idx, (i_mark, i_let, i_occ) in enumerate(inserts):
            if idx not in used_inserts and i_mark == d_mark:
                ops.append(
                    MarkMoved(
                        char=d_mark,
                        from_letter=d_let,
                        from_occurrence=d_occ,
                        to_letter=i_let,
                        to_occurrence=i_occ,
                    )
                )
                used_inserts.add(idx)
                paired = True
                break
        if not paired:
            ops.append(
                MarkRemoved(
                    char=d_mark,
                    on_letter=d_let,
                    letter_occurrence=d_occ,
                )
            )
    for idx, (i_mark, i_let, i_occ) in enumerate(inserts):
        if idx not in used_inserts:
            ops.append(
                MarkAdded(
                    char=i_mark,
                    on_letter=i_let,
                    letter_occurrence=i_occ,
                )
            )

    return ops if ops else None


# ── Paseq / legarmeh extraction ──────────────────────────────


def _extract_paseq_ops(old_text, new_text, old_ep=None, new_ep=None):
    """Extract PaseqAdded/PaseqRemoved ops."""
    anchor = _find_paseq_word_anchor(old_text, new_text)
    fragment = _find_paseq_fragment(old_text, new_text) if anchor is None else None

    if old_ep is not None and new_ep is not None:
        old_types = []
        new_types = []
        collect_paseq_types(old_ep, old_types)
        collect_paseq_types(new_ep, new_types)
        old_counts = Counter(old_types)
        new_counts = Counter(new_types)
        deltas = {
            paseq_type: new_counts[paseq_type] - old_counts[paseq_type]
            for paseq_type in set(old_counts) | set(new_counts)
        }
        added = [pt for pt, d in deltas.items() if d > 0]
        removed = [pt for pt, d in deltas.items() if d < 0]
        if len(added) == 1 and not removed:
            return [
                PaseqAdded(
                    paseq_type=added[0],
                    on_word=anchor[0] if anchor else None,
                    word_occurrence=anchor[1] if anchor else None,
                    old_fragment=fragment[0] if fragment else None,
                    new_fragment=fragment[1] if fragment else None,
                )
            ]
        if len(removed) == 1 and not added:
            return [
                PaseqRemoved(
                    paseq_type=removed[0],
                    on_word=anchor[0] if anchor else None,
                    word_occurrence=anchor[1] if anchor else None,
                    old_fragment=fragment[0] if fragment else None,
                    new_fragment=fragment[1] if fragment else None,
                )
            ]
    if not has_paseq(old_text) and has_paseq(new_text):
        return [
            PaseqAdded(
                paseq_type="paseq / legarmeh",
                on_word=anchor[0] if anchor else None,
                word_occurrence=anchor[1] if anchor else None,
                old_fragment=fragment[0] if fragment else None,
                new_fragment=fragment[1] if fragment else None,
            )
        ]
    if has_paseq(old_text) and not has_paseq(new_text):
        return [
            PaseqRemoved(
                paseq_type="paseq / legarmeh",
                on_word=anchor[0] if anchor else None,
                word_occurrence=anchor[1] if anchor else None,
                old_fragment=fragment[0] if fragment else None,
                new_fragment=fragment[1] if fragment else None,
            )
        ]
    return []


def _find_paseq_word_anchor(old_text, new_text):
    old_words = old_text.split(" ")
    new_words = new_text.split(" ")
    if len(old_words) != len(new_words):
        return None

    def _strip_paseq(word):
        return word.replace(PASOLEG, "").replace(DOUB_VERT_LINE, "")

    old_bases = [_strip_paseq(word) for word in old_words]

    for index, (old_word, new_word) in enumerate(zip(old_words, new_words)):
        if old_word == new_word:
            continue
        old_base = _strip_paseq(old_word)
        new_base = _strip_paseq(new_word)
        if old_base != new_base:
            continue
        occurrence = sum(1 for word in old_bases[: index + 1] if word == old_base)
        return old_base, occurrence

    return None


def _find_paseq_fragment(old_text, new_text):
    old_words = old_text.split(" ")
    new_words = new_text.split(" ")

    prefix = 0
    while (
        prefix < len(old_words)
        and prefix < len(new_words)
        and old_words[prefix] == new_words[prefix]
    ):
        prefix += 1

    old_suffix_start = len(old_words)
    new_suffix_start = len(new_words)
    while (
        old_suffix_start > prefix
        and new_suffix_start > prefix
        and old_words[old_suffix_start - 1] == new_words[new_suffix_start - 1]
    ):
        old_suffix_start -= 1
        new_suffix_start -= 1

    if prefix == old_suffix_start and prefix == new_suffix_start:
        return None

    return (
        " ".join(old_words[prefix:old_suffix_start]),
        " ".join(new_words[prefix:new_suffix_start]),
    )


# ── Gray maqaf extraction ───────────────────────────────────


def _extract_maqaf_ops(old_text, new_text):
    """Extract GrayMaqafAdded/GrayMaqafRemoved ops."""
    old_count = old_text.count(NU_GMAQ)
    new_count = new_text.count(NU_GMAQ)
    diff = new_count - old_count
    if diff > 0:
        return [GrayMaqafAdded() for _ in range(diff)]
    if diff < 0:
        return [GrayMaqafRemoved() for _ in range(-diff)]
    return []


# ── Structural extraction ───────────────────────────────────


def _extract_structural_ops(old_ep, new_ep):
    """Extract TemplateAdded/Removed/Restructured ops."""
    added, removed = template_name_multiset_delta(old_ep, new_ep)
    ops = []
    for name in added:
        ops.append(TemplateAdded(name=name))
    for name in removed:
        ops.append(TemplateRemoved(name=name))
    if not ops:
        ops.append(TemplateRestructured())
    return ops


# ── Public API ───────────────────────────────────────────────


def extract_change_ops(
    old_text, new_text, category, book, chapter, verse, old_ep=None, new_ep=None
):
    """Extract a list of ChangeOps describing this diff.

    The returned ops can be:
    - rendered to English via change_ops_render.render_english()
    - mechanically applied via change_ops_apply.apply_text_ops()
    """
    poetic = is_poetic(book, chapter, verse)

    if category == "maqaf-afor":
        ops = _extract_maqaf_ops(old_text, new_text)
        # Check if gray maqaf ops fully explain the change
        intermediate = apply_text_ops(old_text, ops)
        if intermediate == new_text:
            return ops
        # Try mark extraction for secondary changes (meteg, rafe, etc.)
        mark_ops = _extract_mark_ops(intermediate, new_text, is_mark)
        if mark_ops:
            combined = ops + mark_ops
            if apply_text_ops(old_text, combined) == new_text:
                return combined
        # Try accent extraction for secondary accent changes
        accent_ops = _extract_mark_ops(intermediate, new_text, is_accent)
        if accent_ops:
            combined = ops + accent_ops
            if apply_text_ops(old_text, combined) == new_text:
                return combined
        # Fall back: catch-all replacement for the residual
        return ops + [
            GenericTextReplace(old_fragment=intermediate, new_fragment=new_text)
        ]

    if category == "legarmeih-paseq":
        return _extract_paseq_ops(old_text, new_text, old_ep, new_ep)

    if category in ACCENT_CATS:
        ops = _extract_mark_ops(old_text, new_text, is_accent)
        if ops:
            return ops
        return [GenericTextReplace(old_fragment=old_text, new_fragment=new_text)]

    if category in MARK_CATS:
        ops = _extract_mark_ops(old_text, new_text, is_mark)
        if ops:
            return ops
        return [GenericTextReplace(old_fragment=old_text, new_fragment=new_text)]

    if category == "misc":
        # Try accents first, then marks
        ops = _extract_mark_ops(old_text, new_text, is_accent)
        if ops:
            return ops
        ops = _extract_mark_ops(old_text, new_text, is_mark)
        if ops:
            return ops
        return [GenericTextReplace(old_fragment=old_text, new_fragment=new_text)]

    # Structural categories (dehi-removal, tsinnor-removal, template-change)
    if old_ep is not None and new_ep is not None:
        return _extract_structural_ops(old_ep, new_ep)

    return [GenericTextReplace(old_fragment=old_text, new_fragment=new_text)]
