# Initially generated by GitHub Copilot.
"""Render ChangeOps to English description strings.

Consumes the structured ChangeOps produced by change_ops_extract and
produces the same English text the pipeline produced before the
extraction/rendering split.

Imports name tables and formatting helpers from describe_diff without
modifying that module.

Exports:
    render_english — produce an English description from a list of ChangeOps
"""

from pydiff_mpplus.change_ops import (
    ComplexReplace,
    GenericReplace,
    GenericTextReplace,
    GrayMaqafAdded,
    GrayMaqafRemoved,
    MarkAdded,
    MarkMoved,
    MarkRemoved,
    MarkReplaced,
    MarkReordered,
    PaseqAdded,
    PaseqRemoved,
    TemplateAdded,
    TemplateRemoved,
    TemplateRestructured,
    is_text_op,
)
from pydiff_mpplus.describe_diff import (
    accent_name,
    is_accent,
    is_poetic,
    letter_name,
    letter_ref,
    mark_name,
    ordinal,
)

# ── Helpers ──────────────────────────────────────────────────


def _name_for(ch, poetic):
    """Return the display name for a mark/accent character."""
    if is_accent(ch):
        return accent_name(ch, poetic=poetic)
    return mark_name(ch)


def _render_one(op, poetic, old_letter_counts=None, new_letter_counts=None):
    """Render a single ChangeOp to an English fragment."""
    if old_letter_counts is None:
        old_letter_counts = {}
    if new_letter_counts is None:
        new_letter_counts = {}

    if isinstance(op, MarkMoved):
        force_ordinal = op.from_letter == op.to_letter and (
            old_letter_counts.get(op.from_letter, 0) > 1
            or new_letter_counts.get(op.to_letter, 0) > 1
        )
        return (
            f"{_name_for(op.char, poetic)}"
            f" on {letter_ref(op.from_letter, op.from_occurrence, old_letter_counts, force_ordinal=force_ordinal)}"
            f" in old,"
            f" on {letter_ref(op.to_letter, op.to_occurrence, new_letter_counts, force_ordinal=force_ordinal)}"
            f" in new"
        )

    if isinstance(op, MarkReplaced):
        return (
            f"on {letter_name(op.on_letter)}, "
            f"{_name_for(op.old_char, poetic)} in old → "
            f"{_name_for(op.new_char, poetic)} in new"
        )

    if isinstance(op, GenericReplace):
        return (
            f"{_name_for(op.old_char, poetic)} on {letter_name(op.old_letter)}"
            f" (old) → {_name_for(op.new_char, poetic)} on "
            f"{letter_name(op.new_letter)} (new)"
        )

    if isinstance(op, ComplexReplace):
        old_parts = ", ".join(
            f"{_name_for(m, poetic)} on {letter_name(l)}"
            for m, l, _occ in op.old_qualified
        )
        new_parts = ", ".join(
            f"{_name_for(m, poetic)} on {letter_name(l)}"
            for m, l, _occ in op.new_qualified
        )
        return f"old has {old_parts}; new has {new_parts}"

    if isinstance(op, MarkRemoved):
        return f"{_name_for(op.char, poetic)} on {letter_name(op.on_letter)} removed"

    if isinstance(op, MarkAdded):
        return f"{_name_for(op.char, poetic)} on {letter_name(op.on_letter)} added"

    if isinstance(op, MarkReordered):
        names = [_name_for(ch, poetic) for ch in op.chars]
        order_word = "opposite" if len(names) == 2 else "different"
        return f"{','.join(names)} in old" f" appears in the {order_word} order in new"

    if isinstance(op, GrayMaqafAdded):
        return "add gray maqaf"

    if isinstance(op, GrayMaqafRemoved):
        return "remove gray maqaf"

    if isinstance(op, PaseqAdded):
        return f"add {op.paseq_type}"

    if isinstance(op, PaseqRemoved):
        return f"remove {op.paseq_type}"

    if isinstance(op, GenericTextReplace):
        # This is a fallback — not rendered to English, it means
        # the change was not decomposed.  Return None so the caller
        # can decide what to show.
        return None

    if isinstance(op, TemplateAdded):
        return None  # structural ops handled by mpplus_html directly

    if isinstance(op, TemplateRemoved):
        return None

    if isinstance(op, TemplateRestructured):
        return None

    return None


# ── Public API ───────────────────────────────────────────────


def render_english(ops, book, chapter, verse, old_text="", new_text=""):
    """Render a list of ChangeOps to an English description string.

    Returns None if no ops produce English output (e.g. all structural
    or all GenericTextReplace).

    *old_text* and *new_text* are used only to compute letter counts
    for ordinal disambiguation (e.g. "2nd mem").
    """
    from collections import Counter

    poetic = is_poetic(book, chapter, verse)

    old_letter_counts = Counter(ch for ch in old_text if 0x05D0 <= ord(ch) <= 0x05EA)
    new_letter_counts = Counter(ch for ch in new_text if 0x05D0 <= ord(ch) <= 0x05EA)

    descriptions = []
    for op in ops:
        if not is_text_op(op):
            continue
        desc = _render_one(op, poetic, old_letter_counts, new_letter_counts)
        if desc is not None:
            descriptions.append(desc)

    return "; ".join(descriptions) if descriptions else None
