# Initially generated by GitHub Copilot.
"""Update vendored py/pycmn and py/pydiff_mpp from MAM-basics.

Run from repo root:
    .venv\Scripts\python.exe py\main_update_vendored_files.py

For each vendored package the script:
  1. Determines which local files to update (intersection of what already
     exists locally and what exists in the MAM-basics source directory).
  2. Copies those files verbatim from MAM-basics.
  3. Writes (or overwrites) provenance.md in the local package directory,
     recording the MAM-basics git commit, tag, copy date, and file list.
"""

import datetime
import shutil
import subprocess
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_MAM = _REPO.parent / "MAM-basics"

_VENDORED_PACKAGES = [
    ("pycmn", Path("py/pycmn"), Path("py/pycmn")),
    ("pydiff_mpp", Path("py/pydiff_mpp"), Path("py/pydiff_mpp")),
]


def _get_mam_git_info() -> tuple[str, str | None]:
    """Return (commit_hash, tag_or_None) for MAM-basics HEAD."""
    commit = subprocess.run(
        ["git", "-C", str(_MAM), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()

    tag_result = subprocess.run(
        ["git", "-C", str(_MAM), "describe", "--tags", "--exact-match", "HEAD"],
        capture_output=True,
        text=True,
    )
    tag = tag_result.stdout.strip() if tag_result.returncode == 0 else None
    return commit, tag


def _copy_by_intersection(src_dir: Path, dest_dir: Path) -> list[str]:
    """Copy .py files present in dest_dir from src_dir.

    Skips provenance.md and non-.py files.
    If __init__.py is present locally but absent in src_dir, skips it silently
    (local-only package stub).  For any other local .py file absent in src_dir,
    raises FileNotFoundError.
    Returns sorted list of copied filenames.
    """
    copied: list[str] = []
    for dest_file in sorted(dest_dir.iterdir()):
        if dest_file.suffix != ".py":
            continue
        src_file = src_dir / dest_file.name
        if not src_file.exists():
            if dest_file.name == "__init__.py":
                continue  # local-only package stub; not vendored from MAM-basics
            raise FileNotFoundError(
                f"{dest_file.name} exists locally but not in MAM-basics source "
                f"{src_dir} — has the file been removed upstream?"
            )
        shutil.copy2(src_file, dest_file)
        copied.append(dest_file.name)
    return copied


def _write_provenance(
    dest_dir: Path,
    mam_src_rel: str,
    copied_files: list[str],
    commit: str,
    tag: str | None,
    date_str: str,
) -> None:
    """Write provenance.md into dest_dir."""
    pkg_name = dest_dir.name
    lines = [
        f"Provenance of {pkg_name}/",
        "",
        "These Python files were copied from MAM-basics at:",
        "",
        f"  GitRepos-relative path: MAM-basics/{mam_src_rel}",
        "",
        "Files copied:",
    ]
    for fname in copied_files:
        lines.append(f"  {fname}")
    lines.append("")
    lines.append(f"Git commit: {commit}")
    if tag is not None:
        lines.append(f"Git tag:    {tag}")
    lines.append("")
    lines.append(f"Date copied: {date_str}")
    lines.append("")

    provenance_path = dest_dir / "provenance.md"
    provenance_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    if not _MAM.is_dir():
        raise FileNotFoundError(
            f"MAM-basics repo not found at {_MAM}. "
            "Expected as a sibling of this repo."
        )

    commit, tag = _get_mam_git_info()
    date_str = datetime.date.today().isoformat()

    for _pkg_name, mam_src_rel, local_rel in _VENDORED_PACKAGES:
        src_dir = _MAM / mam_src_rel
        dest_dir = _REPO / local_rel

        if not src_dir.is_dir():
            raise FileNotFoundError(
                f"Source directory not found in MAM-basics: {src_dir}"
            )

        copied = _copy_by_intersection(src_dir, dest_dir)
        _write_provenance(
            dest_dir,
            mam_src_rel.as_posix(),
            copied,
            commit,
            tag,
            date_str,
        )
        print(f"{dest_dir.relative_to(_REPO)}: copied {len(copied)} files")

    print(f"MAM-basics commit: {commit}")
    if tag:
        print(f"MAM-basics tag:    {tag}")


main()
