# Initially generated by GitHub Copilot.
"""Update vendored py/mb_cmn and py/mb_diff_mpu from MAM-basics.

Run from repo root:
    .venv\Scripts\python.exe py\main_update_vendored_files.py

For each vendored package the script:
  1. Determines which local files to update (intersection of what already
     exists locally and what exists in the MAM-basics source directory).
  2. Copies those files verbatim from MAM-basics.
  3. Writes (or overwrites) provenance.md in the local package directory,
     recording the MAM-basics git commit, tag, copy date, and file list.
"""

import datetime
import importlib.util
import sys
from pathlib import Path
from types import ModuleType

_REPO = Path(__file__).resolve().parent.parent
_MAM = _REPO.parent / "MAM-basics"

_VENDORED_PACKAGES = [
    ("mb_cmn", Path("py/mb_cmn"), Path("py/mb_cmn")),
    ("mb_diff_mpu", Path("py/mb_diff_mpu"), Path("py/mb_diff_mpu")),
]


def _load_vendoring_sync() -> ModuleType:
    module_path = _MAM / "py" / "mb_cmn" / "vendoring_sync.py"
    if not module_path.is_file():
        raise FileNotFoundError(
            f"Shared helper not found: {module_path}. "
            "Expected in sibling MAM-basics repo."
        )

    spec = importlib.util.spec_from_file_location("mb_cmn_vendoring_sync", module_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load module spec from {module_path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    if not _MAM.is_dir():
        raise FileNotFoundError(
            f"MAM-basics repo not found at {_MAM}. "
            "Expected as a sibling of this repo."
        )

    vendoring_sync = _load_vendoring_sync()

    commit, tag = vendoring_sync.get_git_info(_MAM)
    date_str = datetime.date.today().isoformat()

    for _pkg_name, mam_src_rel, local_rel in _VENDORED_PACKAGES:
        src_dir = _MAM / mam_src_rel
        dest_dir = _REPO / local_rel

        if not src_dir.is_dir():
            raise FileNotFoundError(
                f"Source directory not found in MAM-basics: {src_dir}"
            )

        copied = vendoring_sync.copy_by_intersection(
            src_dir,
            dest_dir,
            include_suffixes=(".py",),
            strict=True,
        )
        vendoring_sync.write_provenance(
            dest_dir,
            source_rel=f"MAM-basics/{mam_src_rel.as_posix()}",
            copied_files=copied,
            commit=commit,
            tag=tag,
            date_str=date_str,
        )
        print(f"{dest_dir.relative_to(_REPO)}: copied {len(copied)} files")

    print(f"MAM-basics commit: {commit}")
    if tag:
        print(f"MAM-basics tag:    {tag}")


main()
