# Initially generated by GitHub Copilot.
r"""Update the vendored packages and modules under py/ from MAM-basics.

Run from repo root:
    .venv\Scripts\python.exe py\main_update_vendored_files.py

For each vendored package the script:
  1. Determines which local files to update (intersection of what already
     exists locally and what exists in the MAM-basics source directory).
  2. Copies those files verbatim from MAM-basics.
  3. Writes (or overwrites) provenance.md in the local package directory,
     recording the MAM-basics git commit, tag, copy date, and file list.

Two of the vendored modules are single files that sit at the top of py/ rather
than inside a package, because that is where their importers spell them:
uxlc_misc.my_uxlc and uxlc_misc.my_uxlc_page_break_info both say
``import uxlc_paths``. The intersection rule cannot be pointed at py/ itself --
this repo's own py/main_*.py files are there and MAM-basics has none of them --
so those two are named outright in _VENDORED_FILES and share one provenance
record.
"""

import datetime
import shutil
import sys
from pathlib import Path

from mb_cmn import vendoring_sync

_REPO = Path(__file__).resolve().parent.parent
_MAM = _REPO.parent / "MAM-basics"

_VENDORED_PACKAGES = [
    ("mb_cmn", Path("py/mb_cmn"), Path("py/mb_cmn")),
    ("mb_diff_mpu", Path("py/mb_diff_mpu"), Path("py/mb_diff_mpu")),
    ("uxlc_lci", Path("py/uxlc_lci"), Path("py/uxlc_lci")),
    ("uxlc_misc", Path("py/uxlc_misc"), Path("py/uxlc_misc")),
]

# See the module docstring for why these are named rather than intersected.
_VENDORED_FILES = [Path("py/uxlc_paths.py")]
_LOOSE_FILE_DIR = Path("py")


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    if not _MAM.is_dir():
        raise FileNotFoundError(
            f"MAM-basics repo not found at {_MAM}. "
            "Expected as a sibling of this repo."
        )

    commit, tag = vendoring_sync.get_git_info(_MAM)
    date_str = datetime.date.today().isoformat()

    for _pkg_name, mam_src_rel, local_rel in _VENDORED_PACKAGES:
        src_dir = _MAM / mam_src_rel
        dest_dir = _REPO / local_rel

        if not src_dir.is_dir():
            raise FileNotFoundError(
                f"Source directory not found in MAM-basics: {src_dir}"
            )

        copied = vendoring_sync.copy_by_intersection(
            src_dir,
            dest_dir,
            include_suffixes=(".py",),
            strict=True,
        )
        vendoring_sync.write_provenance(
            dest_dir,
            source_rel=f"MAM-basics/{mam_src_rel.as_posix()}",
            copied_files=copied,
            commit=commit,
            tag=tag,
            date_str=date_str,
        )
        print(f"{dest_dir.relative_to(_REPO)}: copied {len(copied)} files")

    _copy_loose_files(commit, tag, date_str)

    print(f"MAM-basics commit: {commit}")
    if tag:
        print(f"MAM-basics tag:    {tag}")


def _copy_loose_files(commit: str, tag: str | None, date_str: str) -> None:
    """Copy the named single-file modules, and record them in one provenance file.

    A missing source raises rather than being skipped: the file is here because
    something imports it, so an absent source means the module moved in
    MAM-basics and this list has to follow it.
    """
    copied: list[str] = []
    for rel_path in _VENDORED_FILES:
        src_file = _MAM / rel_path
        if not src_file.is_file():
            raise FileNotFoundError(f"Source file not found in MAM-basics: {src_file}")
        dest_file = _REPO / rel_path
        shutil.copy2(src_file, dest_file)
        copied.append(dest_file.relative_to(_REPO / _LOOSE_FILE_DIR).as_posix())

    vendoring_sync.write_provenance(
        _REPO / _LOOSE_FILE_DIR,
        source_rel=f"MAM-basics/{_LOOSE_FILE_DIR.as_posix()}",
        copied_files=copied,
        commit=commit,
        tag=tag,
        date_str=date_str,
        title=f"Provenance of the vendored single-file modules in {_LOOSE_FILE_DIR.as_posix()}/",
    )
    print(f"{_LOOSE_FILE_DIR}: copied {len(copied)} files")


main()
