# Initially generated by GitHub Copilot.
from __future__ import annotations

import unicodedata
from difflib import SequenceMatcher
import unittest

from python_modules.mam_uxlc_diff_descriptions import (
    SYMBOL_NAMES,
    describe_simple_qere_change,
)
from python_modules.xaser_malei_diff_descriptions import (
    HEBREW_LETTERS,
    MARK_NAMES,
    describe_xaser_malei_qere_change,
)

# ---------------------------------------------------------------------------
# Constants for the forward-simulation helpers
# ---------------------------------------------------------------------------

DAGESH = "\N{HEBREW POINT DAGESH OR MAPIQ}"
HIRIQ = "\N{HEBREW POINT HIRIQ}"
TSERE = "\N{HEBREW POINT TSERE}"
QAMATS = "\N{HEBREW POINT QAMATS}"
QAMATS_QATAN = "\N{HEBREW POINT QAMATS QATAN}"
HOLAM = "\N{HEBREW POINT HOLAM}"
QUBUTS = "\N{HEBREW POINT QUBUTS}"

_VOWEL_NAME_TO_MARK: dict[str, str] = {name: mark for mark, name in MARK_NAMES.items()}

_MATER_FROM_SUFFIX: dict[str, str] = {
    "qamats-yod": "י",
    "qamats-qatan-yod": "י",
    "tsere-yod": "י",
    "ḥiriq-yod": "י",
    "yod": "י",
    "qamats-vav": "ו",
    "qamats-qatan-vav": "ו",
    "ḥolam-vav": "ו",
    "shuruq": "ו",
    "vav": "ו",
}

_LETTER_FROM_NAME: dict[str, str] = {v: k for k, v in SYMBOL_NAMES.items()}


# ---------------------------------------------------------------------------
# Forward-simulation helpers
# These independently apply the described operation to MAM and predict qere.
# They are "cheating" in that they are given structural parameters extracted
# from the description string, rather than a full parse; but they are NOT
# given qere_text, so the match assertion is non-trivial.
# ---------------------------------------------------------------------------


def _strip_all_points(text: str) -> str:
    return "".join(c for c in text if not unicodedata.combining(c))


def _letters_only(text: str) -> str:
    return "".join(c for c in text if c in HEBREW_LETTERS)


def _skel_positions(text: str) -> list[int]:
    return [i for i, c in enumerate(text) if not unicodedata.combining(c)]


def _combining_after(text: str, pos: int) -> list[str]:
    marks: list[str] = []
    for i in range(pos + 1, len(text)):
        if unicodedata.combining(text[i]):
            marks.append(text[i])
        else:
            break
    return marks


def _predict_xaser_malei_insert(
    mam_text: str,
    *,
    old_vowel: str,
    new_suffix: str,
    after_letter: str | None = None,
) -> str:
    """Return predicted qere SKELETON by inserting the mater described.

    Finds the letter in MAM that bears `old_vowel` (and optionally matches
    `after_letter`), then inserts the new mater after it.
    """
    vowel_mark = _VOWEL_NAME_TO_MARK[old_vowel]
    new_mater = _MATER_FROM_SUFFIX[new_suffix]
    skel_mam = _strip_all_points(mam_text)
    positions = _skel_positions(mam_text)
    for skel_idx, char_pos in enumerate(positions):
        letter = mam_text[char_pos]
        marks = _combining_after(mam_text, char_pos)
        if vowel_mark in marks:
            if after_letter is None or letter == after_letter:
                return skel_mam[: skel_idx + 1] + new_mater + skel_mam[skel_idx + 1 :]
    raise AssertionError(
        f"Vowel {old_vowel!r} not found in {mam_text!r}"
        + (f" on letter {after_letter!r}" if after_letter else "")
    )


def _predict_letter_remove(mam_text: str, *, letter_name: str) -> str:
    """Return predicted qere LETTER skeleton by removing one instance of letter."""
    char = _LETTER_FROM_NAME[letter_name]
    letters = _letters_only(mam_text)
    idx = letters.index(char)
    return letters[:idx] + letters[idx + 1 :]


def _predict_letter_replace(
    mam_text: str,
    *,
    old_name: str,
    new_name: str,
    after_letter: str | None = None,
) -> str:
    """Return predicted qere LETTER skeleton by replacing old letter with new.

    When `after_letter` is given, replaces the instance of old_name that
    immediately follows after_letter (needed when old_name appears multiple times).
    """
    old_char = _LETTER_FROM_NAME[old_name]
    new_char = _LETTER_FROM_NAME[new_name]
    letters = _letters_only(mam_text)
    if after_letter is not None:
        for i, c in enumerate(letters):
            if c == old_char and i > 0 and letters[i - 1] == after_letter:
                return letters[:i] + new_char + letters[i + 1 :]
        raise AssertionError(
            f"Letter {old_name!r} not found immediately after {after_letter!r}"
            f" in {letters!r}"
        )
    idx = letters.index(old_char)
    return letters[:idx] + new_char + letters[idx + 1 :]


def _predict_letter_add_at_end(mam_text: str, *, letter_name: str) -> str:
    return _letters_only(mam_text) + _LETTER_FROM_NAME[letter_name]


def _predict_letter_add_after(mam_text: str, *, new_name: str, after_name: str) -> str:
    new_char = _LETTER_FROM_NAME[new_name]
    after_char = _LETTER_FROM_NAME[after_name]
    letters = _letters_only(mam_text)
    # Insert after the LAST occurrence of after_char
    idx = letters.rindex(after_char)
    return letters[: idx + 1] + new_char + letters[idx + 1 :]


def _predict_spelling_replace(
    mam_text: str,
    qere_text: str,
    *,
    old_spelling: str,
    new_spelling: str,
) -> str:
    """Verify a mater-swap (replace opcode) and return the predicted qere skeleton.

    Unlike the other helpers this consults qere_text only for the opcode
    position — the mater identity check is independent.
    """
    old_mater = _MATER_FROM_SUFFIX[old_spelling]
    new_mater = _MATER_FROM_SUFFIX[new_spelling]
    skel_mam = _strip_all_points(mam_text)
    skel_qere = _strip_all_points(qere_text)
    for tag, i1, i2, j1, j2 in SequenceMatcher(
        None, skel_mam, skel_qere, autojunk=False
    ).get_opcodes():
        if tag == "replace":
            assert skel_mam[i1:i2] == old_mater, (
                f"Expected old mater {old_mater!r} at opcode, "
                f"found {skel_mam[i1:i2]!r}"
            )
            assert skel_qere[j1:j2] == new_mater, (
                f"Expected new mater {new_mater!r} at opcode, "
                f"found {skel_qere[j1:j2]!r}"
            )
            return skel_mam[:i1] + new_mater + skel_mam[i2:]
    raise AssertionError(
        f"No replace opcode found between {mam_text!r} and {qere_text!r}"
    )


def _grapheme_clusters(text: str) -> list[str]:
    clusters: list[str] = []
    for char in text:
        if not clusters or not unicodedata.combining(char):
            clusters.append(char)
            continue
        clusters[-1] += char
    return clusters


def _cluster_marks(cluster: str) -> list[str]:
    return list(cluster[1:])


def _predict_qubuts_shuruq_hiriq_haser(mam_text: str) -> str:
    clusters = _grapheme_clusters(mam_text)
    for index in range(len(clusters) - 2):
        current_cluster = clusters[index]
        first_yod = clusters[index + 1]
        second_yod = clusters[index + 2]
        current_marks = _cluster_marks(current_cluster)
        first_yod_marks = _cluster_marks(first_yod)
        second_yod_marks = _cluster_marks(second_yod)
        if QUBUTS not in current_marks:
            continue
        if first_yod[0] != "י" or second_yod[0] != "י":
            continue
        if HIRIQ not in first_yod_marks or HIRIQ in second_yod_marks:
            continue

        transformed = list(clusters)
        transformed[index] = current_cluster[0] + "".join(
            mark for mark in current_marks if mark != QUBUTS
        )
        transformed[index + 1] = "ו" + DAGESH
        transformed[index + 2] = "י" + "".join(first_yod_marks + second_yod_marks)
        return "".join(transformed)

    raise AssertionError(f"Composite qubuts/shuruq pattern not found in {mam_text!r}")


# ---------------------------------------------------------------------------
# Assertions
# ---------------------------------------------------------------------------


def _assert_xaser_malei_insert(
    tc: unittest.TestCase,
    mam: str,
    qere: str,
    expected_desc: str,
    *,
    old_vowel: str,
    new_suffix: str,
    after_letter: str | None = None,
) -> None:
    tc.assertEqual(describe_xaser_malei_qere_change(mam, qere), expected_desc)
    predicted = _predict_xaser_malei_insert(
        mam, old_vowel=old_vowel, new_suffix=new_suffix, after_letter=after_letter
    )
    tc.assertEqual(
        predicted, _strip_all_points(qere), msg=f"Forward simulation failed for {mam!r}"
    )


def _assert_letter_remove(
    tc: unittest.TestCase,
    mam: str,
    qere: str,
    expected_desc: str,
    *,
    letter_name: str,
) -> None:
    desc = describe_simple_qere_change(word=mam, qere=qere, verse="Numbers 1:1.1")
    tc.assertEqual(desc, expected_desc)
    predicted = _predict_letter_remove(mam, letter_name=letter_name)
    tc.assertEqual(
        predicted, _letters_only(qere), msg=f"Forward simulation failed for {mam!r}"
    )


def _assert_letter_replace(
    tc: unittest.TestCase,
    mam: str,
    qere: str,
    expected_desc: str,
    *,
    old_name: str,
    new_name: str,
    after_letter: str | None = None,
    verse: str = "Numbers 1:1.1",
) -> None:
    desc = describe_simple_qere_change(word=mam, qere=qere, verse=verse)
    tc.assertEqual(desc, expected_desc)
    predicted = _predict_letter_replace(
        mam, old_name=old_name, new_name=new_name, after_letter=after_letter
    )
    tc.assertEqual(
        predicted, _letters_only(qere), msg=f"Forward simulation failed for {mam!r}"
    )


def _assert_letter_add_at_end(
    tc: unittest.TestCase,
    mam: str,
    qere: str,
    expected_desc: str,
    *,
    letter_name: str,
) -> None:
    desc = describe_simple_qere_change(word=mam, qere=qere, verse="Numbers 1:1.1")
    tc.assertEqual(desc, expected_desc)
    predicted = _predict_letter_add_at_end(mam, letter_name=letter_name)
    tc.assertEqual(
        predicted, _letters_only(qere), msg=f"Forward simulation failed for {mam!r}"
    )


def _assert_letter_add_after(
    tc: unittest.TestCase,
    mam: str,
    qere: str,
    expected_desc: str,
    *,
    new_name: str,
    after_name: str,
) -> None:
    desc = describe_simple_qere_change(word=mam, qere=qere, verse="Numbers 1:1.1")
    tc.assertEqual(desc, expected_desc)
    predicted = _predict_letter_add_after(mam, new_name=new_name, after_name=after_name)
    tc.assertEqual(
        predicted, _letters_only(qere), msg=f"Forward simulation failed for {mam!r}"
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class XaserMaleiInsertTests(unittest.TestCase):
    """xaser→malei: UXLC qere adds one mater lectionis that MAM lacks."""

    def test_tsere_to_tsere_yod(self) -> None:
        # Row 1 — unique tsere; "after bet" no longer emitted
        _assert_xaser_malei_insert(
            self,
            "וּבֵנָ֔יו",
            "וּבֵינָ֔יו",
            "replace tsere with tsere-yod",
            old_vowel="tsere",
            new_suffix="tsere-yod",
        )

    def test_qamats_to_qamats_yod_unique(self) -> None:
        # Row 4 — single qamats
        _assert_xaser_malei_insert(
            self,
            "חֲסִידָו֙",
            "חֲסִידָיו֙",
            "replace qamats with qamats-yod",
            old_vowel="qamats",
            new_suffix="qamats-yod",
        )

    def test_qamats_to_qamats_yod_after_nun(self) -> None:
        # Row 8 — two qamats in the word; "after nun" needed
        _assert_xaser_malei_insert(
            self,
            "בָּנָ֣ו",
            "בָּנָ֣יו",
            "replace qamats with qamats-yod after nun",
            old_vowel="qamats",
            new_suffix="qamats-yod",
            after_letter="נ",
        )

    def test_holam_to_holam_vav(self) -> None:
        # Row 23 — unique ḥolam; "after yod" no longer emitted
        _assert_xaser_malei_insert(
            self,
            "וְאַחְיֹתֵיהֶ֖ם",
            "וְאַחְיוֹתֵיהֶ֖ם",
            "replace ḥolam with ḥolam-vav",
            old_vowel="ḥolam",
            new_suffix="ḥolam-vav",
        )

    def test_qubuts_to_shuruq(self) -> None:
        # Row 39 — replaces qubuts (no mater) with shuruq (vav+dagesh)
        _assert_xaser_malei_insert(
            self,
            "מְשֻׁבוֹתֵיהֶֽם׃",
            "מְשׁוּבוֹתֵיהֶֽם׃",
            "replace qubuts with shuruq",
            old_vowel="qubuts",
            new_suffix="shuruq",
        )

    def test_hiriq_to_hiriq_yod(self) -> None:
        # Row 77 — unique ḥiriq; "after yod" no longer emitted
        _assert_xaser_malei_insert(
            self,
            "גּוֹיִ֖",
            "גּוֹיִ֖י",
            "replace ḥiriq with ḥiriq-yod",
            old_vowel="ḥiriq",
            new_suffix="ḥiriq-yod",
        )


class SpellingSwapTests(unittest.TestCase):
    """xaser↔malei where both spellings are meaningful (replace opcode at skeleton)."""

    def test_hiriq_yod_to_shuruq(self) -> None:
        # Row 25 — the pointed text combines two adjacent subchanges.
        mam = "בְּמַחֲלֻיִ֣ים"
        qere = "בְּמַחֲלוּיִ֣ם"
        expected = (
            "replace qubuts with shuruq; "
            "replace ḥiriq-yod with ḥiriq"
        )
        self.assertEqual(describe_xaser_malei_qere_change(mam, qere), expected)
        predicted = _predict_qubuts_shuruq_hiriq_haser(mam)
        self.assertEqual(predicted, qere)


class LetterRemoveTests(unittest.TestCase):
    """UXLC qere removes one consonant that MAM has."""

    def test_remove_alef_unique(self) -> None:
        # Row 2 — single alef; "after vav" no longer emitted
        _assert_letter_remove(
            self,
            "הֶהָלְכ֣וּא",
            "הֶהָלְכ֣וּ",
            "remove alef",
            letter_name="alef",
        )

    def test_remove_alef_after_resh(self) -> None:
        # Row 13 — he appears twice; row has single alef though
        # (resh is unique in context; verifies "after resh" is NOT emitted)
        _assert_letter_remove(
            self,
            "וַיֹּר֨אוּ",
            "וַיֹּר֨וּ",
            "remove alef",
            letter_name="alef",
        )

    def test_remove_alef_multiple_context(self) -> None:
        # Row 74
        _assert_letter_remove(
            self,
            "וְנִרְפּ֥אוּ",
            "וְנִרְפּ֥וּ",
            "remove alef",
            letter_name="alef",
        )


class LetterReplaceTests(unittest.TestCase):
    """UXLC qere replaces one consonant with another."""

    def test_he_to_vav_unique_he(self) -> None:
        # Row 34 — single he; "after resh" no longer emitted
        _assert_letter_replace(
            self,
            "שִׁירֹ֣ה",
            "שִׁיר֣וֹ",
            "replace he with vav",
            old_name="he",
            new_name="vav",
            verse="Psalms 42:9.6",
        )

    def test_he_to_vav_multiple_he(self) -> None:
        # Row 21 — three he's; "after resh" is genuinely needed
        _assert_letter_replace(
            self,
            "וְהִזְהִירֹ֖ה",
            "וְהִזְהִיר֖וֹ",
            "replace he with vav after resh",
            old_name="he",
            new_name="vav",
            after_letter="ר",
            verse="Ezekiel 3:18.7",
        )

    def test_alef_to_yod_unique(self) -> None:
        # Row 45 — single alef; "after pe" no longer emitted
        _assert_letter_replace(
            self,
            "רִפִּ֤אנוּ",
            "רִפִּ֣ינוּ",
            "replace alef with yod",
            old_name="alef",
            new_name="yod",
            verse="Jeremiah 51:9.1",
        )


class LetterAddTests(unittest.TestCase):
    """UXLC qere adds a consonant that MAM lacks."""

    def test_add_alef_at_end(self) -> None:
        # Row 12
        _assert_letter_add_at_end(
            self,
            "וְהַמֵּבִ֖י",
            "וְהַמֵּבִ֖יא",
            "add alef at end",
            letter_name="alef",
        )

    def test_add_alef_after_tsadi(self) -> None:
        # Row 27
        _assert_letter_add_after(
            self,
            "יָצָ֜תִי",
            "יָצָ֜אתִי",
            "add alef after tsadi",
            new_name="alef",
            after_name="tsadi",
        )


if __name__ == "__main__":
    unittest.main()
