# Initially generated by GitHub Copilot.
from __future__ import annotations

import unittest

from py_render.rt_validate_qyv import evaluate_qyv_row


class QyvValidationTests(unittest.TestCase):
    def test_matches_basic_qyv_case(self) -> None:
        evaluation = evaluate_qyv_row(
            {
                "row_number": 4,
                "verse": "1Samuel 2:9.2",
                "word": "חֲסִידָו֙",
                "notes-UXLC": "חסידו חֲסִידָיו֙",
            }
        )

        self.assertTrue(evaluation.matches)
        self.assertEqual(evaluation.expected_qere, "חֲסִידָיו֙")

    def test_matches_qyv_case_with_final_punctuation(self) -> None:
        evaluation = evaluate_qyv_row(
            {
                "row_number": 55,
                "verse": "Ezekiel 40:26.13",
                "word": "אֵילָֽו",
                "notes-UXLC": "אילו אֵילָֽיו׃",
            }
        )

        self.assertTrue(evaluation.matches)

    def test_matches_qyv_case_with_meteg_difference(self) -> None:
        evaluation = evaluate_qyv_row(
            {
                "row_number": 18,
                "verse": "2Samuel 24:14.14",
                "word": "רַחֲמָ֔ו",
                "notes-UXLC": "רחמו רַֽחֲמָ֔יו",
            }
        )

        self.assertTrue(evaluation.matches)

    def test_rejects_non_qyv_qere(self) -> None:
        evaluation = evaluate_qyv_row(
            {
                "row_number": 4,
                "verse": "1Samuel 2:9.2",
                "word": "חֲסִידָו֙",
                "notes-UXLC": "חסידו חֲסִידָו֙",
            }
        )

        self.assertFalse(evaluation.matches)
        self.assertIn("violates expected qere", str(evaluation.reason))


if __name__ == "__main__":
    unittest.main()
