# Initially generated by GitHub Copilot.
from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from python_modules.verify_table_notes_in_uxlc import verify_table_notes_in_uxlc


class VerifyTableNotesInUXLCTests(unittest.TestCase):
    def test_verify_table_notes_in_uxlc_accepts_known_buggy_joshua_qere(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir_name:
            tmp_dir = Path(tmp_dir_name)
            uxlc_dir = tmp_dir / "UXLC-utils" / "in" / "UXLC-39"
            uxlc_dir.mkdir(parents=True)
            (uxlc_dir / "Joshua.xml").write_text(
                """
<Tanach>
  <c n="10">
    <v n="24">
      <w>הַמִּלְחָמָה֙</w>
      <k>ההלכוא<x>y</x></k>
      <q>הֶהָלְכ֣וְּּ</q>
      <w>אִתּ֔וֹ</w>
    </v>
  </c>
</Tanach>
""".strip(),
                encoding="utf-8",
            )
            table_json_path = tmp_dir / "table_data.json"
            table_json_path.write_text(
                json.dumps(
                    {
                        "table": {
                            "rows": [
                                {
                                    "row_number": 2,
                                    "verse": "Joshua 10:24.19",
                                    "notes-UXLC": "ההלכוא הֶהָלְכ֣וּ",
                                }
                            ]
                        }
                    },
                    ensure_ascii=False,
                ),
                encoding="utf-8",
            )

            report = verify_table_notes_in_uxlc(
                table_json_path=table_json_path,
                uxlc_utils_path=tmp_dir / "UXLC-utils",
            )

        self.assertEqual(report["summary"]["rows_missing_claim_count"], 0)
        row_report = report["rows"][0]
        self.assertEqual(
            row_report["uxlc_verse_tokens"],
            ["הַמִּלְחָמָה֙", "ההלכוא", "הֶהָלְכ֣וְּּ", "אִתּ֔וֹ"],
        )
        self.assertEqual(row_report["ketiv_match_source_tags"], ["k"])
        self.assertEqual(row_report["qere_match_source_tags"], ["q"])
        self.assertTrue(row_report["found_qere_claim_via_known_uxlc_bug"])

    def test_verify_table_notes_in_uxlc_merges_maqaf_with_following_ketiv(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir_name:
            tmp_dir = Path(tmp_dir_name)
            uxlc_dir = tmp_dir / "UXLC-utils" / "in" / "UXLC-39"
            uxlc_dir.mkdir(parents=True)
            (uxlc_dir / "Samuel_1.xml").write_text(
                """
<Tanach>
  <c n="30">
    <v n="6">
      <w>עַל־</w>
      <k>בנו</k>
      <q>בָּנָ֣יו</q>
    </v>
  </c>
</Tanach>
""".strip(),
                encoding="utf-8",
            )
            table_json_path = tmp_dir / "table_data.json"
            table_json_path.write_text(
                json.dumps(
                    {
                        "table": {
                            "rows": [
                                {
                                    "row_number": 8,
                                    "verse": "1Samuel 30:6.15",
                                    "notes-UXLC": "עַל־בנו בָּנָ֣יו",
                                }
                            ]
                        }
                    },
                    ensure_ascii=False,
                ),
                encoding="utf-8",
            )

            report = verify_table_notes_in_uxlc(
                table_json_path=table_json_path,
                uxlc_utils_path=tmp_dir / "UXLC-utils",
            )

        self.assertEqual(report["summary"]["rows_missing_claim_count"], 0)
        row_report = report["rows"][0]
        self.assertEqual(row_report["uxlc_verse_tokens"], ["עַל־בנו", "בָּנָ֣יו"])
        self.assertEqual(row_report["ketiv_match_source_tags"], ["w", "k"])
        self.assertEqual(row_report["qere_match_source_tags"], ["q"])

    def test_verify_table_notes_in_uxlc_keeps_split_ketiv_and_qere_sequences_separate(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir_name:
            tmp_dir = Path(tmp_dir_name)
            uxlc_dir = tmp_dir / "UXLC-utils" / "in" / "UXLC-39"
            uxlc_dir.mkdir(parents=True)
            (uxlc_dir / "Isaiah.xml").write_text(
                """
<Tanach>
  <tanach>
    <c n="52">
      <v n="5">
        <k>מי־</k>
        <k>לי־</k>
        <q>מַה־</q>
        <q>לִּי־</q>
        <w>פֹה֙</w>
      </v>
    </c>
  </tanach>
</Tanach>
""".strip(),
                encoding="utf-8",
            )
            table_json_path = tmp_dir / "table_data.json"
            table_json_path.write_text(
                json.dumps(
                    {
                        "table": {
                            "rows": [
                                {
                                    "row_number": 37,
                                    "verse": "Isaiah 52:5.2",
                                    "notes-UXLC": "מי־לי־ מַה־לִּי־",
                                }
                            ]
                        }
                    },
                    ensure_ascii=False,
                ),
                encoding="utf-8",
            )

            report = verify_table_notes_in_uxlc(
                table_json_path=table_json_path,
                uxlc_utils_path=tmp_dir / "UXLC-utils",
            )

        self.assertEqual(report["summary"]["rows_missing_claim_count"], 0)
        self.assertEqual(
            report["rows"][0]["uxlc_verse_tokens"],
            ["מי־לי־", "מַה־לִּי־", "פֹה֙"],
        )

    def test_verify_table_notes_in_uxlc_ignores_cgj_in_qere_surface_text(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir_name:
            tmp_dir = Path(tmp_dir_name)
            uxlc_dir = tmp_dir / "UXLC-utils" / "in" / "UXLC-39"
            uxlc_dir.mkdir(parents=True)
            (uxlc_dir / "Ezekiel.xml").write_text(
                """
<Tanach>
  <tanach>
    <c n="40">
      <v n="36">
        <k>ואלמו</k>
        <q>וְאֽ͏ֵלַמָּ֔יו</q>
      </v>
    </c>
  </tanach>
</Tanach>
""".strip(),
                encoding="utf-8",
            )
            table_json_path = tmp_dir / "table_data.json"
            table_json_path.write_text(
                json.dumps(
                    {
                        "table": {
                            "rows": [
                                {
                                    "row_number": 70,
                                    "verse": "Ezekiel 40:36.3",
                                    "notes-UXLC": "ואלמו וְאֵֽלַמָּ֔יו",
                                }
                            ]
                        }
                    },
                    ensure_ascii=False,
                ),
                encoding="utf-8",
            )

            report = verify_table_notes_in_uxlc(
                table_json_path=table_json_path,
                uxlc_utils_path=tmp_dir / "UXLC-utils",
            )

        self.assertEqual(report["summary"]["rows_missing_claim_count"], 0)


if __name__ == "__main__":
    unittest.main()
