# Initially generated by GitHub Copilot.
from __future__ import annotations

import unittest

from python_modules.refresh_table_row_github_issues import (
    build_refreshed_row_github_issues,
    normalize_issue_tags,
    render_table_row_github_issues_module_text,
)
from python_modules.table_row_github_issues import RowGitHubIssueMetadata


class RefreshTableRowGitHubIssuesTests(unittest.TestCase):
    def test_normalizes_supported_labels_only(self) -> None:
        self.assertEqual(
            normalize_issue_tags(["documentation", "rafeh", "QyV"]),
            ("qyv", "rafe"),
        )

    def test_builds_refreshed_row_metadata_and_module_text(self) -> None:
        existing_rows = {
            "1": RowGitHubIssueMetadata(issue_number=12, is_closed=False, tags=()),
        }
        live_issues = {
            12: {
                "number": 12,
                "state": "CLOSED",
                "labels": [
                    {"name": "ḥolam he"},
                    {"name": "documentation"},
                ],
            }
        }

        refreshed_rows = build_refreshed_row_github_issues(
            existing_rows=existing_rows,
            live_issues=live_issues,
        )

        self.assertEqual(
            refreshed_rows["1"],
            RowGitHubIssueMetadata(
                issue_number=12,
                is_closed=True,
                tags=("holam-he",),
            ),
        )

        module_text = render_table_row_github_issues_module_text(refreshed_rows)
        self.assertIn(
            "'1': RowGitHubIssueMetadata(issue_number=12, is_closed=True, tags=('holam-he',)),",
            module_text,
        )
        self.assertIn("ISSUE_LABEL_TO_TAG", module_text)


if __name__ == "__main__":
    unittest.main()
