# Initially generated by GitHub Copilot.
from __future__ import annotations

import unittest

from py_render.rt_validate_holam_he import evaluate_holam_he_row


class HolamHeValidationTests(unittest.TestCase):
    def test_matches_basic_holam_he_case(self) -> None:
        evaluation = evaluate_holam_he_row(
            {
                "row_number": 34,
                "verse": "Psalms 42:9.6",
                "word": "שִׁירֹ֣ה",
                "notes-UXLC": "שירה שִׁיר֣וֹ",
            }
        )

        self.assertTrue(evaluation.matches)
        self.assertEqual(evaluation.expected_qere, "שִׁירֹ֣ו")

    def test_matches_holam_he_case_with_final_punctuation(self) -> None:
        evaluation = evaluate_holam_he_row(
            {
                "row_number": 76,
                "verse": "Ezekiel 48:21.35",
                "word": "בְּתוֹכֹֽה׃",
                "notes-UXLC": "בתוכה בְּתוֹכֽוֹ׃",
            }
        )

        self.assertTrue(evaluation.matches)

    def test_rejects_non_holam_he_qere(self) -> None:
        evaluation = evaluate_holam_he_row(
            {
                "row_number": 34,
                "verse": "Psalms 42:9.6",
                "word": "שִׁירֹ֣ה",
                "notes-UXLC": "שירה שִׁירֹ֣ה",
            }
        )

        self.assertFalse(evaluation.matches)
        self.assertIn("violates expected qere", str(evaluation.reason))


if __name__ == "__main__":
    unittest.main()
