# Initially generated by GitHub Copilot.
from __future__ import annotations

from pathlib import Path
import tempfile
import unittest
import zipfile

from python_modules.extract_docx_xml_utils import export_images


class ExtractDocxXmlUtilsTests(unittest.TestCase):
    def test_export_images_allows_idempotent_rerun_for_same_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir_name:
            tmp_dir = Path(tmp_dir_name)
            archive_path = _build_test_archive(tmp_dir, b"docx-image-bytes")
            image_dir = tmp_dir / "img"
            image_dir.mkdir()

            with zipfile.ZipFile(archive_path) as archive:
                export_images(
                    archive=archive,
                    row_number=13,
                    column_key="aleppo",
                    targets=["media/image25.png"],
                    image_dir=image_dir,
                    repo_root=tmp_dir,
                )

            with zipfile.ZipFile(archive_path) as archive:
                rel_paths = export_images(
                    archive=archive,
                    row_number=13,
                    column_key="aleppo",
                    targets=["media/image25.png"],
                    image_dir=image_dir,
                    repo_root=tmp_dir,
                )

        self.assertEqual(rel_paths, ["img/row013_aleppo_01.png"])

    def test_export_images_refuses_to_overwrite_manual_edit(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir_name:
            tmp_dir = Path(tmp_dir_name)
            archive_path = _build_test_archive(tmp_dir, b"docx-image-bytes")
            image_dir = tmp_dir / "img"
            image_dir.mkdir()
            output_path = image_dir / "row015_aleppo_01.png"
            output_path.write_bytes(b"manually-edited-bytes")

            with zipfile.ZipFile(archive_path) as archive:
                with self.assertRaisesRegex(
                    ValueError,
                    "refusing to overwrite existing extracted image with different bytes",
                ):
                    export_images(
                        archive=archive,
                        row_number=15,
                        column_key="aleppo",
                        targets=["media/image25.png"],
                        image_dir=image_dir,
                        repo_root=tmp_dir,
                    )

            self.assertEqual(output_path.read_bytes(), b"manually-edited-bytes")

    def test_export_images_preserves_explicit_manual_override_paths(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir_name:
            tmp_dir = Path(tmp_dir_name)
            repo_root = tmp_dir / "repo"
            archive_path = _build_test_archive(tmp_dir, b"docx-image-bytes")
            image_dir = repo_root / "gh-pages" / "img"
            image_dir.mkdir(parents=True)
            output_path = image_dir / "row013_aleppo_01.png"
            output_path.write_bytes(b"manually-edited-bytes")

            with zipfile.ZipFile(archive_path) as archive:
                rel_paths = export_images(
                    archive=archive,
                    row_number=13,
                    column_key="aleppo",
                    targets=["media/image25.png"],
                    image_dir=image_dir,
                    repo_root=repo_root,
                )

            preserved_bytes = output_path.read_bytes()

        self.assertEqual(rel_paths, ["gh-pages/img/row013_aleppo_01.png"])
        self.assertEqual(preserved_bytes, b"manually-edited-bytes")


def _build_test_archive(tmp_dir: Path, image_bytes: bytes) -> Path:
    archive_path = tmp_dir / "test.docx"
    with zipfile.ZipFile(archive_path, "w") as archive:
        archive.writestr("word/media/image25.png", image_bytes)
    return archive_path


if __name__ == "__main__":
    unittest.main()
