# Initially generated by GitHub Copilot.
from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
import unittest

from python_modules.refresh_table_row_github_issues import (
    build_refreshed_row_github_issues,
    normalize_issue_tags,
    row_github_issues_payload,
)
from python_modules.json_io import write_json
from python_modules.table_row_github_issues import (
    RowGitHubIssueMetadata,
    load_row_github_issues,
    reload_row_github_issues,
    row_github_issue_is_closed,
)


class RefreshTableRowGitHubIssuesTests(unittest.TestCase):
    def test_normalizes_supported_labels_only(self) -> None:
        self.assertEqual(
            normalize_issue_tags(["documentation", "rafeh", "QyV"]),
            ("qyv", "rafeh"),
        )

    def test_builds_refreshed_row_metadata_and_json_payload(self) -> None:
        existing_rows = {
            "1": RowGitHubIssueMetadata(issue_number=12, is_closed=False, tags=()),
        }
        live_issues = {
            12: {
                "number": 12,
                "state": "CLOSED",
                "labels": [
                    {"name": "ḥolam he"},
                    {"name": "documentation"},
                ],
            }
        }

        refreshed_rows = build_refreshed_row_github_issues(
            existing_rows=existing_rows,
            live_issues=live_issues,
        )

        self.assertEqual(
            refreshed_rows["1"],
            RowGitHubIssueMetadata(
                issue_number=12,
                is_closed=True,
                tags=("holam-he",),
            ),
        )

        payload = row_github_issues_payload(refreshed_rows)
        self.assertEqual(
            payload,
            {
                "1": {
                    "issue_number": 12,
                    "is_closed": True,
                    "tags": ["holam-he"],
                }
            },
        )

    def test_loads_typed_row_metadata_from_json(self) -> None:
        with TemporaryDirectory() as tmp_dir:
            json_path = Path(tmp_dir) / "table_row_github_issues.json"
            write_json(
                json_path,
                {
                    "1": {
                        "issue_number": 12,
                        "is_closed": True,
                        "tags": ["holam-he"],
                    }
                },
            )

            loaded_rows = load_row_github_issues(json_path)

        self.assertEqual(
            loaded_rows,
            {
                "1": RowGitHubIssueMetadata(
                    issue_number=12,
                    is_closed=True,
                    tags=("holam-he",),
                )
            },
        )

    def test_reloads_module_cache_after_json_update(self) -> None:
        with TemporaryDirectory() as tmp_dir:
            json_path = Path(tmp_dir) / "table_row_github_issues.json"
            baseline_rows = load_row_github_issues()
            try:
                write_json(
                    json_path,
                    {
                        "1": {
                            "issue_number": 12,
                            "is_closed": False,
                            "tags": ["holam-he"],
                        }
                    },
                )
                reload_row_github_issues(json_path)
                self.assertFalse(row_github_issue_is_closed("1"))

                write_json(
                    json_path,
                    {
                        "1": {
                            "issue_number": 12,
                            "is_closed": True,
                            "tags": ["holam-he"],
                        }
                    },
                )
                reload_row_github_issues(json_path)
                self.assertTrue(row_github_issue_is_closed("1"))
            finally:
                write_json(
                    json_path,
                    {
                        row_number: {
                            "issue_number": metadata.issue_number,
                            "is_closed": metadata.is_closed,
                            "tags": list(metadata.tags),
                        }
                        for row_number, metadata in baseline_rows.items()
                    },
                )
                reload_row_github_issues()


if __name__ == "__main__":
    unittest.main()
