# Initially generated by GitHub Copilot.
from __future__ import annotations

import unittest

from py_render.rt_matching_tmpl_args import mpp_template_calls_by_row_number


class MppTemplateCallsByRowNumberTests(unittest.TestCase):
    def test_synthesizes_single_lamed_qere_pair(self) -> None:
        payload = {
            "mam_plus_rows_matching_mpp_verse_template_arg": [
                {
                    "row_number": 74,
                    "matching_template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "וְנִרְפּ֥אֿוּ",
                        }
                    ],
                    "template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "וְנִרְפּ֥אֿוּ",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "2",
                            "argument_text": "ל-קרי=וְנִרְפּ֥וּ",
                        },
                    ],
                }
            ]
        }

        self.assertEqual(
            mpp_template_calls_by_row_number(payload),
            {"74": ['{{קו"כ-אם|וְנִרְפּ֥אֿוּ|ל-קרי=וְנִרְפּ֥וּ}}']},
        )

    def test_prefers_explicit_nusakh_call_over_synthesis(self) -> None:
        payload = {
            "mam_plus_rows_matching_mpp_verse_template_arg": [
                {
                    "row_number": 2,
                    "matching_template_args_in_mpp_verse": [
                        {
                            "template_name": 'כו"ק',
                            "argument_key": "2",
                            "argument_text": "הֶהָלְכ֣וּ",
                        }
                    ],
                    "template_args_in_mpp_verse": [
                        {
                            "template_name": "נוסח",
                            "argument_key": "1",
                            "argument_text": '{{כו"ק|ההלכוא|הֶהָלְכ֣וּ}}',
                        },
                        {
                            "template_name": 'כו"ק',
                            "argument_key": "1",
                            "argument_text": "ההלכוא",
                        },
                        {
                            "template_name": 'כו"ק',
                            "argument_key": "2",
                            "argument_text": "הֶהָלְכ֣וּ",
                        },
                    ],
                }
            ]
        }

        self.assertEqual(
            mpp_template_calls_by_row_number(payload),
            {"2": ['{{כו"ק|ההלכוא|הֶהָלְכ֣וּ}}']},
        )

    def test_synthesizes_anchored_first_occurrence_from_multi_occurrence_verse(
        self,
    ) -> None:
        payload = {
            "mam_plus_rows_matching_mpp_verse_template_arg": [
                {
                    "row_number": 13,
                    "matching_template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "וַיֹּר֨אֿוּ",
                        }
                    ],
                    "template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "וַיֹּר֨אֿוּ",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "2",
                            "argument_text": "ל-קרי=וַיֹּר֨וּ",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "הַמּוֹרִ֤אֿים",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "2",
                            "argument_text": "ל-קרי=הַמּוֹרִ֤ים",
                        },
                    ],
                }
            ]
        }

        self.assertEqual(
            mpp_template_calls_by_row_number(payload),
            {"13": ['{{קו"כ-אם|וַיֹּר֨אֿוּ|ל-קרי=וַיֹּר֨וּ}}']},
        )

    def test_synthesizes_anchored_second_occurrence_from_multi_occurrence_verse(
        self,
    ) -> None:
        payload = {
            "mam_plus_rows_matching_mpp_verse_template_arg": [
                {
                    "row_number": 14,
                    "matching_template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "הַמּוֹרִ֤אֿים",
                        }
                    ],
                    "template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "וַיֹּר֨אֿוּ",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "2",
                            "argument_text": "ל-קרי=וַיֹּר֨וּ",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "הַמּוֹרִ֤אֿים",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "2",
                            "argument_text": "ל-קרי=הַמּוֹרִ֤ים",
                        },
                    ],
                }
            ]
        }

        self.assertEqual(
            mpp_template_calls_by_row_number(payload),
            {"14": ['{{קו"כ-אם|הַמּוֹרִ֤אֿים|ל-קרי=הַמּוֹרִ֤ים}}']},
        )

    def test_returns_no_synthesized_call_for_ambiguous_repeated_match(self) -> None:
        payload = {
            "mam_plus_rows_matching_mpp_verse_template_arg": [
                {
                    "row_number": 91,
                    "matching_template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "אָמְבִיג",
                        }
                    ],
                    "template_args_in_mpp_verse": [
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "אָמְבִיג",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "2",
                            "argument_text": "ל-קרי=אֶחָד",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "1",
                            "argument_text": "אָמְבִיג",
                        },
                        {
                            "template_name": 'קו"כ-אם',
                            "argument_key": "2",
                            "argument_text": "ל-קרי=שֵׁנִי",
                        },
                    ],
                }
            ]
        }

        self.assertEqual(mpp_template_calls_by_row_number(payload), {"91": []})


if __name__ == "__main__":
    unittest.main()
