# Initially generated by GitHub Copilot.
"""Helpers for Hebrew Wikisource page and diff URLs."""

from mb_cmn.url_percent import pct_fragment, pct_path_component

_HE_WIKISOURCE_PAGE_BASE = "https://he.wikisource.org/wiki"
_HE_WIKISOURCE_DIFF_BASE = "https://he.wikisource.org/w/index.php"


def he_page_url(path: str, fragment: str | None = None) -> str:
    """Build a Hebrew Wikisource page URL from readable inputs."""
    out = f"{_HE_WIKISOURCE_PAGE_BASE}/{pct_path_component(path, safe='/:')}"
    if fragment is None:
        return out
    return f"{out}#{pct_fragment(fragment)}"


def he_taamim_url(name_he: str, chapter_he: str) -> str:
    """Build a Hebrew Wikisource ta'amim page URL."""
    return he_page_url(f"{name_he}_{chapter_he}/טעמים")


def he_diff_url(title: str, diff: str | int, oldid: str | int) -> str:
    """Build a Hebrew Wikisource diff URL without double-encoding."""
    title_enc = pct_path_component(title)
    return f"{_HE_WIKISOURCE_DIFF_BASE}?" f"title={title_enc}&diff={diff}&oldid={oldid}"
