# Initially generated by GitHub Copilot.
"""Small URL percent-encoding helpers for escape-boundary usage."""

from urllib import parse


def pct_path_component(text: str, safe: str = "") -> str:
    """Percent-encode a URL path/title component."""
    return parse.quote(text, safe=safe)


def pct_fragment(text: str, safe: str = "") -> str:
    """Percent-encode a URL fragment payload when needed."""
    return parse.quote(text, safe=safe)
