# Initially generated by GitHub Copilot.
from __future__ import annotations

from pathlib import Path

import hkq_paths

# Badge and swatch colours, taken in order and wrapping only past the end. The
# UXLC-corrections report draws all three of its filter columns from one cursor
# through this list, so it needs as many distinct colours as it has filters --
# 17 at present -- or two columns shown side by side repeat a colour and the
# eye reads sameness of colour as sameness of category. Entries beyond the
# tenth were appended for that; the first ten are what the ketiv/qere report
# has always used and their order is load-bearing there.
PALETTE = [
    "#1f5f8b",
    "#2e8b57",
    "#a2472f",
    "#6a4c93",
    "#7a5f00",
    "#3e6b7f",
    "#8b3a62",
    "#4f6d2e",
    "#505c91",
    "#9c4a22",
    "#1d6f6f",
    "#7b4b8a",
    "#8a5a1f",
    "#3c5f3c",
    "#93334a",
    "#2f5d8f",
    "#6b6320",
    "#7a3a2a",
    "#3f5a75",
    "#5c4a8c",
]

ASSETS_DIR = hkq_paths.assets_dir()
CSS_TEMPLATE_PATH = ASSETS_DIR / "table_data_findings.css"
JS_TEMPLATE_PATH = ASSETS_DIR / "table_data_findings.js"
CSS_COLOR_PLACEHOLDER = "/* __FINDING_COLORS__ */"


def write_report_assets(
    css_output_path: Path,
    js_output_path: Path,
    finding_ids: list[str],
) -> None:
    color_rules = "\n".join(
        f".cat-{finding_id} {{ background: {PALETTE[idx % len(PALETTE)]}; }}"
        for idx, finding_id in enumerate(finding_ids)
    )

    css_template = CSS_TEMPLATE_PATH.read_text(encoding="utf-8")
    css_text = css_template.replace(CSS_COLOR_PLACEHOLDER, color_rules)
    js_text = JS_TEMPLATE_PATH.read_text(encoding="utf-8")

    css_output_path.parent.mkdir(parents=True, exist_ok=True)
    js_output_path.parent.mkdir(parents=True, exist_ok=True)
    css_output_path.write_text(css_text, encoding="utf-8", newline="")
    js_output_path.write_text(js_text, encoding="utf-8", newline="")
