# Initially generated by GitHub Copilot.
from __future__ import annotations

from html import escape
import re

from py_render.rt_render_utils import contains_hebrew_char

HEBREW_LETTER_PATTERN = re.compile(r"[\u05D0-\u05EA]+")

COMPARISON_LABEL_TOOLTIPS = {
    "MAM-docx": "MAM Word (from docx)",
    "MAM-mpu": "MAM Word (from latest MAM-parsed-plus)",
}


def build_comparison_rows(
    *,
    word: str,
    notes_uxlc: str,
    notes_haketer: str | None,
    template_rows: list[dict[str, str]] | None,
    differing_latest_mpu_words: list[str],
) -> list[dict[str, str]] | None:
    ketiv_qere = _split_notes_uxlc(notes_uxlc)
    if ketiv_qere is None:
        return None

    haketer_rows: list[dict[str, str]] = []
    if notes_haketer is not None:
        haketer_ketiv, haketer_qere = _split_notes_uxlc(notes_haketer)
        if haketer_ketiv is None or haketer_qere is None:
            raise ValueError(
                "expected exactly 2 HaKeter tokens, got "
                f"{notes_haketer.split()!r} from {notes_haketer!r}"
            )
        haketer_rows = [
            {"name": "HaKeter ketiv", "value": haketer_ketiv},
            {"name": "HaKeter qere", "value": haketer_qere},
        ]

    mam_rows = [{"name": "MAM Word", "value": word}]
    if differing_latest_mpu_words:
        mam_rows = [
            {"name": "MAM-docx", "value": word},
            {"name": "MAM-mpu", "value": " | ".join(differing_latest_mpu_words)},
        ]

    rows = [
        *mam_rows,
        *(template_rows or []),
        {"name": "UXLC ketiv", "value": ketiv_qere[0]},
        {"name": "UXLC qere", "value": ketiv_qere[1]},
        *haketer_rows,
    ]
    return _with_comparison_references(rows)


def comparison_table_html(rows: list[dict[str, str]]) -> str:
    body_rows_html = "\n".join(
        (
            "<tr>\n"
            f'<td class="comparison-name-col">{_comparison_label_html(row["name"])}<'
            "/td>\n"
            f'<td class="comparison-value-col">{_comparison_literal_value_html(row["value"])}<'
            "/td>\n"
            f'<td class="comparison-symval-col">{_comparison_symval_html(row["symval"])}<'
            "/td>\n"
            "<"
            "/tr>"
        )
        for row in rows
    )
    return (
        '<table class="comparison-table">\n'
        "<thead>\n<tr>\n<th>name<"
        "/th>\n<th>value<"
        "/th>\n<th>symval<"
        "/th>\n<"
        "/tr>\n<"
        "/thead>\n"
        f"<tbody>\n{body_rows_html}\n<"
        "/tbody>\n<"
        "/table>"
    )


def template_rows_from_supported_qere_wrapper(
    wrapper: dict[str, str] | None,
) -> list[dict[str, str]] | None:
    if wrapper is None:
        return None
    template_name = wrapper.get("template_name")
    ketiv = wrapper.get("ketiv")
    qere = wrapper.get("qere")
    if template_name is None or ketiv is None or qere is None:
        return None
    return [
        {"name": f"{template_name}[כ]", "value": ketiv},
        {"name": f"{template_name}[ק]", "value": qere},
    ]


def _split_notes_uxlc(notes_uxlc: str) -> tuple[str, str] | None:
    tokens = notes_uxlc.split()
    if len(tokens) != 2:
        return None
    return tokens[0], tokens[1]


def _hebrew_letters_only(text: str) -> str:
    return "".join(HEBREW_LETTER_PATTERN.findall(text))


def _find_stripped_reference_name(rows: list[dict[str, str]], value: str) -> str | None:
    stripped_value = _hebrew_letters_only(value)
    if not stripped_value:
        return None
    for prior_row in rows:
        if _hebrew_letters_only(prior_row["value"]) == stripped_value:
            return prior_row["name"]
    return None


def _with_comparison_references(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    first_name_by_value: dict[str, str] = {}
    rendered_rows: list[dict[str, str]] = []
    prior_rows: list[dict[str, str]] = []

    for row in rows:
        value = row["value"]
        literal_value = value
        symval = ""
        reference_name = first_name_by_value.get(value)
        if reference_name is None:
            if row["name"] == "UXLC ketiv":
                stripped_reference_name = _find_stripped_reference_name(
                    prior_rows, value
                )
                if stripped_reference_name is not None:
                    literal_value = ""
                    symval = f"{stripped_reference_name} stripped"
                else:
                    first_name_by_value[value] = row["name"]
            else:
                first_name_by_value[value] = row["name"]
        else:
            literal_value = ""
            symval = reference_name
        rendered_rows.append(
            {
                "name": row["name"],
                "value": literal_value,
                "symval": symval,
            }
        )
        prior_rows.append(row)
    return rendered_rows


def _comparison_literal_value_html(text: str) -> str:
    if not text:
        return ""
    if contains_hebrew_char(text):
        return f'<bdi class="pointed-heb">{escape(text)}</bdi>'
    return f"<span>{escape(text)}</span>"


def _comparison_symval_html(text: str) -> str:
    if not text:
        return ""
    return f"<span>{_comparison_label_html(text)}</span>"


def _comparison_label_html(text: str) -> str:
    label, suffix = _comparison_label_parts(text)
    if label is None:
        return escape(text)
    tooltip = escape(COMPARISON_LABEL_TOOLTIPS[label])
    return (
        f'<abbr class="comparison-label" title="{tooltip}">{escape(label)}</abbr>'
        f"{escape(suffix)}"
    )


def _comparison_label_parts(text: str) -> tuple[str | None, str]:
    for label in COMPARISON_LABEL_TOOLTIPS:
        if text == label:
            return label, ""
        prefix = f"{label} "
        if text.startswith(prefix):
            return label, text[len(label) :]
    return None, ""
