# Initially generated by GitHub Copilot.
from __future__ import annotations

from html import escape
import re

from py_render.rt_render_utils import contains_hebrew_char
from python_modules.qere_projection import qere_arg_key_for_template

SIMPLE_QERE_TEMPLATE_PATTERN = re.compile(
    r"^\{\{(?P<template>[^|{}]+)\|(?P<ketiv>[^{}|]+)\|ל-קרי=(?P<qere>[^{}|]+)\}\}$"
)
POSITIONAL_QERE_TEMPLATE_PATTERN = re.compile(
    r"^\{\{(?P<template>[^|{}]+)\|(?P<arg1>[^{}|]+)\|(?P<arg2>[^{}|]+)\}\}$"
)


def build_comparison_rows(
    *,
    word: str,
    notes_uxlc: str,
    template_calls: list[str],
    differing_latest_mpp_words: list[str],
) -> list[dict[str, str]] | None:
    if differing_latest_mpp_words:
        return None

    split_template_rows = _split_template_rows(template_calls)
    if split_template_rows is None:
        return None

    ketiv_qere = _split_notes_uxlc(notes_uxlc)
    if ketiv_qere is None:
        return None

    rows = [
        {"name": "MAM Word", "value": word},
        *split_template_rows,
        {"name": "UXLC ketiv", "value": ketiv_qere[0]},
        {"name": "UXLC qere", "value": ketiv_qere[1]},
    ]
    return _with_comparison_references(rows)


def comparison_table_html(rows: list[dict[str, str]]) -> str:
    body_rows_html = "".join(
        "<tr>"
        f'<td class="comparison-name-col">{escape(row["name"])}</td>'
        f'<td class="comparison-value-col">{_comparison_value_html(row)}</td>'
        "</tr>"
        for row in rows
    )
    return (
        '<table class="comparison-table">'
        "<thead><tr><th>name</th><th>value</th></tr></thead>"
        f"<tbody>{body_rows_html}</tbody></table>"
    )


def _split_template_rows(template_calls: list[str]) -> list[dict[str, str]] | None:
    if len(template_calls) != 1:
        return None

    call = template_calls[0].strip()
    match = SIMPLE_QERE_TEMPLATE_PATTERN.fullmatch(call)
    if match is not None:
        template_name = match.group("template")
        return [
            {"name": f"{template_name}[כ]", "value": match.group("ketiv")},
            {"name": f"{template_name}[ק]", "value": match.group("qere")},
        ]

    positional_match = POSITIONAL_QERE_TEMPLATE_PATTERN.fullmatch(call)
    if positional_match is None:
        return None

    template_name = positional_match.group("template")
    qere_arg_key = qere_arg_key_for_template(template_name)
    if qere_arg_key != "2":
        return None
    return [
        {"name": f"{template_name}[כ]", "value": positional_match.group("arg1")},
        {"name": f"{template_name}[ק]", "value": positional_match.group("arg2")},
    ]


def _split_notes_uxlc(notes_uxlc: str) -> tuple[str, str] | None:
    tokens = notes_uxlc.split()
    if len(tokens) != 2:
        return None
    return tokens[0], tokens[1]


def _with_comparison_references(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    first_name_by_value: dict[str, str] = {}
    rendered_rows: list[dict[str, str]] = []

    for row in rows:
        value = row["value"]
        display_value = value
        value_is_reference = ""
        reference_name = first_name_by_value.get(value)
        if reference_name is None:
            first_name_by_value[value] = row["name"]
        else:
            display_value = reference_name
            value_is_reference = "1"
        rendered_rows.append(
            {
                "name": row["name"],
                "value": display_value,
                "value_is_reference": value_is_reference,
            }
        )
    return rendered_rows


def _comparison_value_html(row: dict[str, str]) -> str:
    text = row["value"]
    if row.get("value_is_reference") == "1":
        return f"<span>{escape(text)}</span>"
    if contains_hebrew_char(text):
        return f'<bdi class="pointed-heb">{escape(text)}</bdi>'
    return f"<span>{escape(text)}</span>"
