# Initially generated by GitHub Copilot.
from __future__ import annotations

from html import escape

from py_render.rt_render_utils import contains_hebrew_char


def external_link_html(*, href: str, label: str) -> str:
    return (
        f"<a\n"
        f'href="{escape(href)}"\n'
        f'target="_blank"\n'
        f'rel="noopener"\n'
        f">{escape(label)}</a>"
    )


def join_nonempty_html_blocks(*blocks: str) -> str:
    return "\n".join(block for block in blocks if block)


def note_line_html(label: str, value: str, strip_prefix: str | None = None) -> str:
    display_value = value.strip()
    if strip_prefix is not None and display_value.startswith(strip_prefix):
        display_value = display_value[len(strip_prefix) :].lstrip()

    if contains_hebrew_char(display_value):
        value_html = f'<bdi class="pointed-heb">{escape(display_value)}</bdi>'
    else:
        value_html = f"<span>{escape(display_value)}</span>"

    return f'<div class="note-line"><span class="label">{escape(label)}</span> {value_html}</div>'


def record_category_badge_html(*, filter_id: str, label: str) -> str:
    return (
        f'<span class="finding-badge cat-{escape(filter_id)}">'
        f"{escape(label)}</span>"
    )
