# Initially generated by GitHub Copilot.
from __future__ import annotations

from python_modules.table_row_github_issues import ISSUE_TAG_DISPLAY_TEXT

NO_ISSUE_TAG = "no-issue-tag"
NO_ISSUE_TAG_LABEL = "no issue tag"
HOLAM_HE_TAG = "holam-he"
QYV_TAG = "qyv"
ISSUE_TAG_ORDER = (
    "holam-he",
    "qyv",
    "boa-sans-aleph",
    "rafeh",
    NO_ISSUE_TAG,
)


def issue_tag_filter_id(issue_tag: str) -> str:
    return f"issue-tag-{issue_tag}"


def issue_tag_display_text(issue_tag: str) -> str:
    return ISSUE_TAG_DISPLAY_TEXT.get(issue_tag, issue_tag)


def ordered_issue_tags(issue_tags: list[str]) -> list[str]:
    known_tags = [issue_tag for issue_tag in ISSUE_TAG_ORDER if issue_tag in issue_tags]
    extra_tags = sorted(
        issue_tag for issue_tag in issue_tags if issue_tag not in ISSUE_TAG_ORDER
    )
    return known_tags + extra_tags


def record_issue_tags(issue_tags: list[str]) -> list[str]:
    ordered_tags = ordered_issue_tags(issue_tags)
    return ordered_tags if ordered_tags else [NO_ISSUE_TAG]
