# Initially generated by GitHub Copilot.
from __future__ import annotations

from difflib import SequenceMatcher
import re
from typing import Mapping

from mb_cmn.hebrew_punctuation import SOPA
from mb_diff_mpu.describe_diff import describe_change
from mb_diff_mpu.grapheme_diff import grapheme_clusters

from python_modules.extract_docx_notes import parse_verse_reference, standard_book_name
from py_render.rt_xaser_malei_diff_descriptions import (
    describe_xaser_malei_qere_change,
    reduce_xaser_malei_mark_differences,
)

HEBREW_LETTER_OR_MAQAF_PATTERN = re.compile(r"[א-ת־]")
QYV_TAG = "qyv"
HOLAM_HE_TAG = "holam-he"
MAX_SIMPLE_CHUNK_LENGTH = 2

SYMBOL_NAMES = {
    "א": "alef",
    "ב": "bet",
    "ג": "gimel",
    "ד": "dalet",
    "ה": "he",
    "ו": "vav",
    "ז": "zayin",
    "ח": "het",
    "ט": "tet",
    "י": "yod",
    "ך": "final-kaf",
    "כ": "kaf",
    "ל": "lamed",
    "ם": "final-mem",
    "מ": "mem",
    "ן": "final-nun",
    "נ": "nun",
    "ס": "samekh",
    "ע": "ayin",
    "ף": "final-pe",
    "פ": "pe",
    "ץ": "final-tsadi",
    "צ": "tsadi",
    "ק": "qof",
    "ר": "resh",
    "ש": "shin",
    "ת": "tav",
    "־": "maqaf",
}


def simple_row_diff_note_lines(
    row: Mapping[str, object],
    *,
    issue_tags: list[str],
) -> list[tuple[str, str]]:
    if HOLAM_HE_TAG in issue_tags or QYV_TAG in issue_tags:
        return []

    word = _diff_description_word(row)
    notes_uxlc = _as_text(row.get("notes-UXLC"))
    verse = _as_text(row.get("verse"))
    if not word or not notes_uxlc or not verse:
        return []

    ketiv_qere = _split_ketiv_qere(notes_uxlc)
    if ketiv_qere is None:
        return []
    ketiv, qere = ketiv_qere

    note_lines: list[tuple[str, str]] = []
    ketiv_description = describe_simple_ketiv_letters_change(word=word, ketiv=ketiv)
    if ketiv_description is not None:
        note_lines.append(("MAM vs UXLC ketiv letters:", ketiv_description))

    qere_description = describe_simple_qere_change(word=word, qere=qere, verse=verse)
    if qere_description is not None:
        note_lines.append(("MAM vs UXLC qere:", qere_description))
    return note_lines


def _diff_description_word(row: Mapping[str, object]) -> str:
    word_orig = row.get("word_orig")
    if isinstance(word_orig, str) and word_orig:
        return word_orig
    return _as_text(row.get("word"))


def describe_simple_ketiv_letters_change(*, word: str, ketiv: str) -> str | None:
    mam_letters = _letters_and_maqaf(word)
    ketiv_letters = _letters_and_maqaf(ketiv)
    if mam_letters == ketiv_letters:
        return None
    description = _describe_simple_letter_sequence_change(
        old_text=mam_letters,
        new_text=ketiv_letters,
        same_text="same letters as MAM",
    )
    if description is not None:
        return description
    return f"MAM {word}; UXLC ketiv {ketiv}"


def describe_simple_qere_change(*, word: str, qere: str, verse: str) -> str | None:
    word = word.removesuffix(SOPA)
    qere = qere.removesuffix(SOPA)

    if word == qere:
        return None

    xaser_malei_description = describe_xaser_malei_qere_change(word, qere)
    if xaser_malei_description is not None:
        extra_description = _describe_extra_misc_change_after_xaser_malei(
            word=word,
            qere=qere,
            verse=verse,
        )
        if extra_description is None:
            return xaser_malei_description
        return f"{xaser_malei_description} (also {extra_description})"

    if not _has_simple_grapheme_change(word, qere):
        return None

    qere_letters_description = _describe_simple_letter_sequence_change(
        old_text=_letters_and_maqaf(word),
        new_text=_letters_and_maqaf(qere),
        same_text="same letters as MAM",
    )
    if qere_letters_description is None:
        return None
    if qere_letters_description != "same letters as MAM":
        return qere_letters_description

    accent_or_mark_description = _describe_simple_accent_or_mark_change(
        word=word,
        qere=qere,
        verse=verse,
    )
    if accent_or_mark_description is not None:
        return accent_or_mark_description
    return None


def _describe_simple_accent_or_mark_change(
    *, word: str, qere: str, verse: str
) -> str | None:
    return _describe_misc_change(
        old_text=word,
        new_text=qere,
        verse=verse,
        allow_multiple=False,
    )


def _describe_extra_misc_change_after_xaser_malei(
    *, word: str, qere: str, verse: str
) -> str | None:
    reduced_pair = reduce_xaser_malei_mark_differences(word, qere)
    old_text, new_text = reduced_pair if reduced_pair is not None else (word, qere)
    description = _describe_misc_change(
        old_text=old_text,
        new_text=new_text,
        verse=verse,
        allow_multiple=True,
    )
    if description is None:
        return None
    return _format_parenthetical_extra_description(description)


def _describe_misc_change(
    *, old_text: str, new_text: str, verse: str, allow_multiple: bool
) -> str | None:
    book_token, chapter_text, verse_text, _segment = parse_verse_reference(verse)
    description = describe_change(
        old_text,
        new_text,
        "misc",
        standard_book_name(book_token),
        int(chapter_text),
        int(verse_text),
    )
    if description is None:
        return None
    description = _contextualize_mam_uxlc_qere_misc_description(description)
    if not allow_multiple and ";" in description:
        return None
    return description


def _contextualize_mam_uxlc_qere_misc_description(description: str) -> str:
    return (
        description.replace("old has ", "MAM has ")
        .replace("new has ", "UXLC qere has ")
        .replace(" (old)", " (MAM)")
        .replace(" (new)", " (UXLC qere)")
        .replace(" in old", " in MAM")
        .replace(" in new", " in UXLC qere")
    )


def _format_parenthetical_extra_description(description: str) -> str:
    return "; ".join(
        _format_parenthetical_extra_clause(clause) for clause in description.split("; ")
    )


def _format_parenthetical_extra_clause(clause: str) -> str:
    if clause.endswith(" added"):
        return f"add {clause[:-6]}"
    if clause.endswith(" removed"):
        return f"remove {clause[:-8]}"
    return clause


def _split_ketiv_qere(notes_uxlc: str) -> tuple[str, str] | None:
    tokens = notes_uxlc.split()
    if len(tokens) != 2:
        return None
    return tokens[0], tokens[1]


def _letters_and_maqaf(text: str) -> str:
    return "".join(HEBREW_LETTER_OR_MAQAF_PATTERN.findall(text))


def _has_simple_grapheme_change(old_text: str, new_text: str) -> bool:
    old_clusters = grapheme_clusters(old_text)
    new_clusters = grapheme_clusters(new_text)
    non_equal_ops = [
        opcode
        for opcode in SequenceMatcher(
            None,
            old_clusters,
            new_clusters,
            autojunk=False,
        ).get_opcodes()
        if opcode[0] != "equal"
    ]
    return len(non_equal_ops) <= 1


def _describe_simple_letter_sequence_change(
    *,
    old_text: str,
    new_text: str,
    same_text: str,
) -> str | None:
    if not old_text or not new_text:
        return None
    if old_text == new_text:
        return same_text

    opcodes = SequenceMatcher(
        None,
        old_text,
        new_text,
        autojunk=False,
    ).get_opcodes()
    non_equal_ops = [opcode for opcode in opcodes if opcode[0] != "equal"]
    if len(non_equal_ops) == 2:
        transposition_description = _describe_adjacent_transposition(
            old_text=old_text,
            new_text=new_text,
            opcodes=opcodes,
        )
        if transposition_description is not None:
            return transposition_description
    if len(non_equal_ops) != 1:
        return None

    tag, start_old, end_old, start_new, end_new = non_equal_ops[0]
    old_chunk = old_text[start_old:end_old]
    new_chunk = new_text[start_new:end_new]
    if max(len(old_chunk), len(new_chunk)) > MAX_SIMPLE_CHUNK_LENGTH:
        return None

    if tag == "replace" and old_chunk and new_chunk:
        return (
            f"replace {_symbol_sequence_name(old_chunk)} with "
            f"{_symbol_sequence_name(new_chunk)}"
            f"{_position_phrase(old_text, start_old, subject=old_chunk)}"
        )
    if tag == "delete" and old_chunk:
        return (
            f"remove {_symbol_sequence_name(old_chunk)}"
            f"{_position_phrase(old_text, start_old, subject=old_chunk)}"
        )
    if tag == "insert" and new_chunk:
        return (
            f"add {_symbol_sequence_name(new_chunk)}"
            f"{_position_phrase(old_text, start_old)}"
        )
    return None


def _describe_adjacent_transposition(
    *,
    old_text: str,
    new_text: str,
    opcodes: list[tuple[str, int, int, int, int]],
) -> str | None:
    if len(old_text) != len(new_text):
        return None
    for index in range(len(opcodes) - 2):
        first, middle, third = opcodes[index : index + 3]
        if middle[0] != "equal":
            continue
        if middle[2] - middle[1] != 1 or middle[4] - middle[3] != 1:
            continue
        if {first[0], third[0]} != {"insert", "delete"}:
            continue

        moved_chunk = _opcode_chunk(
            opcode=first,
            old_text=old_text,
            new_text=new_text,
        )
        if moved_chunk != _opcode_chunk(
            opcode=third,
            old_text=old_text,
            new_text=new_text,
        ):
            continue
        if len(moved_chunk) != 1:
            continue

        middle_chunk = old_text[middle[1] : middle[2]]
        if first[0] == "insert":
            old_pair = middle_chunk + moved_chunk
            new_pair = moved_chunk + middle_chunk
        else:
            old_pair = moved_chunk + middle_chunk
            new_pair = middle_chunk + moved_chunk

        if len(old_pair) != 2 or new_pair != old_pair[::-1]:
            continue
        return f"swap {_symbol_name(old_pair[0])} and {_symbol_name(old_pair[1])}"
    return None


def _opcode_chunk(
    *,
    opcode: tuple[str, int, int, int, int],
    old_text: str,
    new_text: str,
) -> str:
    tag, start_old, end_old, start_new, end_new = opcode
    if tag == "delete":
        return old_text[start_old:end_old]
    if tag == "insert":
        return new_text[start_new:end_new]
    raise ValueError(f"Unsupported opcode tag for chunk lookup: {tag}")


def _position_phrase(reference_text: str, index: int, subject: str = "") -> str:
    if index <= 0:
        return " at beginning"
    if index >= len(reference_text):
        return " at end"
    # If the subject is a single character that appears only once, the
    # position is already unambiguous — no need for "after X".
    if len(subject) == 1 and reference_text.count(subject) == 1:
        return ""
    previous_symbol = reference_text[index - 1]
    return f" after {_symbol_name(previous_symbol)}"


def _symbol_sequence_name(text: str) -> str:
    return "-".join(_symbol_name(symbol) for symbol in text)


def _symbol_name(symbol: str) -> str:
    return SYMBOL_NAMES[symbol]


def _as_text(value: object) -> str:
    return "" if value is None else str(value)

