# Initially generated by GitHub Copilot.
from __future__ import annotations

from html import escape
import os
from pathlib import Path
from typing import Any

from py_render.rt_comparison_table import (
    build_comparison_rows,
    comparison_table_html,
    template_rows_from_supported_qere_wrapper,
)
from py_render.rt_external_links import verse_external_links
from py_render.rt_html_utils import (
    external_link_html,
    join_nonempty_html_blocks,
    note_line_html,
    record_category_badge_html,
)
from py_render.rt_issue_tags import (
    issue_tag_display_text,
    issue_tag_filter_id,
    record_issue_tags,
)
from py_render.rt_mam_uxlc_diff_descriptions import simple_row_diff_note_lines
from py_render.rt_matching_tmpl_args import (
    matching_template_arguments_in_mpp_verse_by_row_number,
    supported_qere_wrapper_by_row_number,
)
from py_render.rt_render_utils import (
    as_optional_text,
    as_text,
    finding_display_text,
    row_fragment_id,
)
from python_modules.table_row_github_issues import (
    require_row_github_issue_metadata,
    row_github_issue_url,
)

# Per-image display-size tweaks measured against each image's native width.
# Key format: (row_number, witness, image_index_1_based)
IMAGE_NATIVE_SCALE_TWEAKS: dict[tuple[str, str, int], float] = {
    ("4", "aleppo", 1): 0.5,
    ("5", "aleppo", 1): 0.5,
    ("6", "aleppo", 1): 0.5,
    ("7", "aleppo", 1): 0.5,
    ("74", "aleppo", 1): 0.5,
}


def record_card_html(
    row: dict[str, Any],
    finding_id: str,
    output_html_path: Path,
    repo_root: Path,
    matching_template_arguments_by_row_number: dict[str, list[dict[str, str]]],
    supported_qere_wrappers: dict[str, dict[str, str]],
) -> str:
    row_number = as_text(row.get("row_number", ""))
    metadata = require_row_github_issue_metadata(row_number)
    row_fragment_id_value = row_fragment_id(row_number)
    verse = as_text(row.get("verse", ""))
    verse_ref = _verse_ref_html(verse=verse, row_number=row_number)
    word = as_text(row.get("word", ""))
    finding = as_text(row.get("finding", ""))
    finding_display = finding_display_text(finding)
    notes_uxlc = as_text(row.get("notes-UXLC", ""))
    notes_uxlc_yatir = as_optional_text(row.get("notes-UXLC-yatir"))
    notes_haketer = as_optional_text(row.get("notes-HaKeter"))
    raw_images = row.get("image_files")
    images: dict[str, object] = raw_images if isinstance(raw_images, dict) else {}
    matching_template_args_in_mpp_verse = matching_template_arguments_by_row_number.get(
        row_number, []
    )
    record_categories: list[tuple[str, str]] = [(finding_id, finding_display)]
    record_categories.extend(
        (
            issue_tag_filter_id(issue_tag),
            issue_tag_display_text(issue_tag),
        )
        for issue_tag in record_issue_tags(metadata.tags)
    )
    filter_ids_attr = " ".join(filter_id for filter_id, _label in record_categories)
    category_badges_html = "\n".join(
        record_category_badge_html(filter_id=filter_id, label=label)
        for filter_id, label in record_categories
    )
    simple_diff_notes_html = "\n".join(
        note_line_html(label=label, value=value)
        for label, value in simple_row_diff_note_lines(
            row,
            issue_tags=metadata.tags,
        )
    )

    yatir_html = (
        ""
        if notes_uxlc_yatir is None
        else note_line_html(
            label="UXLC yatir:",
            value=notes_uxlc_yatir,
            strip_prefix="yatir ",
        )
    )
    supported_qere_wrapper = supported_qere_wrappers.get(row_number)
    differing_latest_mpp_words: list[str] = []
    for match in matching_template_args_in_mpp_verse:
        argument_text = as_text(match.get("argument_text"))
        if argument_text == word or argument_text in differing_latest_mpp_words:
            continue
        differing_latest_mpp_words.append(argument_text)
    if (
        supported_qere_wrapper is not None
        and not matching_template_args_in_mpp_verse
        and supported_qere_wrapper["qere"] != word
        and supported_qere_wrapper["qere"] not in differing_latest_mpp_words
    ):
        differing_latest_mpp_words.append(supported_qere_wrapper["qere"])
    rendered_mam_words = {word, *differing_latest_mpp_words}
    displayed_matching_template_args_in_mpp_verse = [
        match
        for match in matching_template_args_in_mpp_verse
        if as_text(match.get("argument_text")) not in rendered_mam_words
    ]
    mpp_matching_template_arg_html = "\n".join(
        (
            f'<div class="note-line"><span class="label">'
            f'MPP matching template arg ({escape(as_text(match.get("template_name")))}'
            f'[{escape(as_text(match.get("argument_key")))}]):'
            f'</span><bdi class="pointed-heb">'
            f'{escape(as_text(match.get("argument_text")))}</bdi></div>'
        )
        for match in displayed_matching_template_args_in_mpp_verse
    )
    template_rows = template_rows_from_supported_qere_wrapper(supported_qere_wrapper)
    comparison_rows = build_comparison_rows(
        word=word,
        notes_uxlc=notes_uxlc,
        notes_haketer=notes_haketer,
        template_rows=template_rows,
        differing_latest_mpp_words=differing_latest_mpp_words,
    )
    if comparison_rows is None:
        mam_word_label = (
            "MAM Word (from docx):" if differing_latest_mpp_words else "MAM Word:"
        )
        mam_word_html = (
            f'<div class="note-line"><span class="label">{mam_word_label}</span>'
            f'<bdi class="pointed-heb">{escape(word)}</bdi></div>'
        )
        if differing_latest_mpp_words:
            mam_word_html += (
                f'\n<div class="note-line"><span class="label">MAM Word (from latest MPP):</span>'
                f'<bdi class="pointed-heb">{escape(" | ".join(differing_latest_mpp_words))}</bdi></div>'
            )
        mam_uxlc_html = join_nonempty_html_blocks(
            mam_word_html,
            f'<div class="note-line"><span class="label">UXLC:</span><bdi class="pointed-heb">{escape(notes_uxlc)}</bdi></div>',
        )
    else:
        mam_uxlc_html = comparison_table_html(comparison_rows)
    aleppo = _image_paths_html(
        image_paths=images.get("aleppo"),
        witness="aleppo",
        label="Aleppo",
        row_number=row_number,
        output_html_path=output_html_path,
        repo_root=repo_root,
    )
    leningrad = _image_paths_html(
        image_paths=images.get("leningrad"),
        witness="leningrad",
        label="Leningrad",
        row_number=row_number,
        output_html_path=output_html_path,
        repo_root=repo_root,
    )
    notes_html = join_nonempty_html_blocks(
        simple_diff_notes_html,
        yatir_html,
        mpp_matching_template_arg_html,
    )

    return f"""<article
id="{row_fragment_id_value}"
class="record-card"
data-finding-id="{finding_id}"
data-filter-ids="{escape(filter_ids_attr)}"
>
<div class="record-head">
<a class="record-ref" href="#{row_fragment_id_value}">#{escape(row_number)}</a>
<span class="record-verse">
{verse_ref}
</span>
<span class="category-badges">
{category_badges_html}
</span>
</div>
<div class="record-grid">
<div>
{mam_uxlc_html}
{notes_html}
</div>
<div>
<div class="image-panel">
<div class="image-caption">Aleppo</div>
<div class="image-strip">
{aleppo}
</div>
</div>
<div class="image-panel" style="margin-top:.45rem;">
<div class="image-caption">Leningrad</div>
<div class="image-strip">
{leningrad}
</div>
</div>
</div>
</div>
</article>"""


def _image_paths_html(
    image_paths: object,
    witness: str,
    label: str,
    row_number: str,
    output_html_path: Path,
    repo_root: Path,
) -> str:
    if not isinstance(image_paths, list):
        return f'<span class="label">No {escape(label)} image</span>'

    output_dir = output_html_path.parent.resolve()
    rendered: list[str] = []
    for index, path_obj in enumerate(image_paths, start=1):
        if not isinstance(path_obj, str) or not path_obj.strip():
            continue
        absolute_asset = (repo_root / path_obj.replace("\\", "/")).resolve()
        rel_asset = os.path.relpath(absolute_asset, output_dir).replace("\\", "/")
        rel_asset_html = escape(rel_asset)
        native_scale = IMAGE_NATIVE_SCALE_TWEAKS.get((row_number, witness, index))
        native_scale_attr = ""
        if native_scale is not None:
            native_scale_attr = f'\ndata-native-scale="{native_scale:g}"'
        rendered.append(
            f"<a\n"
            f'href="{rel_asset_html}"\n'
            f'target="_blank"\n'
            f'rel="noopener"\n'
            f">\n"
            f"<img\n"
            f'class="image-thumb"\n'
            f'src="{rel_asset_html}"\n'
            f'alt="{escape(label)} image {index}"{native_scale_attr}\n'
            f">\n"
            f"</a>"
        )

    if not rendered:
        return f'<span class="label">No {escape(label)} image</span>'
    return "\n".join(rendered)


def _verse_ref_html(verse: str, row_number: str) -> str:
    links = verse_external_links(verse)
    parts = [
        escape(verse),
        external_link_html(href=links.mgketer_url, label="mgketer"),
        external_link_html(href=links.mwd_url, label="MwD"),
        external_link_html(href=links.mam_ws_url, label="MAM-ws"),
    ]
    issue_url = row_github_issue_url(row_number)
    if issue_url is not None:
        parts.append(external_link_html(href=issue_url, label="issue"))
    return "\n".join(parts)
