# Initially generated by GitHub Copilot.
from __future__ import annotations

FINDING_INVARIANT_SUFFIX = " | L - Qere"
FINDING_DISPLAY_MAP = {
    "A and L - Qere": "A - Qere note",
}
HEBREW_CHAR_RANGES = (("\u0590", "\u05ff"), ("\ufb1d", "\ufb4f"))


def as_text(value: object) -> str:
    return "" if value is None else str(value)


def as_optional_text(value: object) -> str | None:
    if value is None:
        return None
    text = str(value)
    return text if text else None


def contains_hebrew_char(text: str) -> bool:
    return any(
        start <= char <= end for char in text for start, end in HEBREW_CHAR_RANGES
    )


def finding_display_text(finding: str) -> str:
    if finding.endswith(FINDING_INVARIANT_SUFFIX):
        finding = finding[: -len(FINDING_INVARIANT_SUFFIX)]
    return FINDING_DISPLAY_MAP.get(finding, finding)


def row_fragment_id(row_number: str) -> str:
    return f"row{int(row_number):02d}"


def suppressed_output_path(output_html_path):
    return output_html_path.with_name(
        f"{output_html_path.stem}_suppressed{output_html_path.suffix}"
    )
