# Initially generated by GitHub Copilot.
from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from html import escape
from typing import Any

from py_render.rt_issue_tags import (
    ISSUE_TAG_ORDER,
    issue_tag_display_text,
    issue_tag_filter_id,
    record_issue_tags,
)
from py_render.rt_render_utils import (
    as_text,
    finding_display_text,
)
from python_modules.table_row_github_issues import require_row_github_issue_metadata

MPP_TEMPLATE_FILTER_ID = "has-mpp-template"
MPP_TEMPLATE_FILTER_LABEL = "Has matching MPP template"
SUMMARY_ISSUE_TAG_FILTER_IDS = frozenset(
    {
        "issue-tag-holam-he",
        "issue-tag-qyv",
        "issue-tag-boa-sans-aleph",
        "issue-tag-rafeh",
        "issue-tag-no-issue-tag",
    }
)


@dataclass(frozen=True)
class FilterCategory:
    filter_id: str
    label: str
    count: int


def filter_categories(
    *,
    rows: list[dict[str, Any]],
    sorted_findings: list[tuple[str, int]],
    finding_ids: dict[str, str],
    matching_template_arguments_by_row_number: dict[str, list[dict[str, str]]],
) -> list[FilterCategory]:
    categories: list[FilterCategory] = []
    finding_counts = Counter(as_text(row.get("finding", "")) for row in rows)
    for finding, _count in sorted_findings:
        count = finding_counts.get(finding, 0)
        if count == 0:
            continue
        categories.append(
            FilterCategory(
                filter_id=finding_ids[finding],
                label=finding_display_text(finding),
                count=count,
            )
        )

    mpp_template_filter_count = sum(
        1
        for row in rows
        if matching_template_arguments_by_row_number.get(
            as_text(row.get("row_number", "")), []
        )
    )
    if mpp_template_filter_count:
        categories.append(
            FilterCategory(
                filter_id=MPP_TEMPLATE_FILTER_ID,
                label=MPP_TEMPLATE_FILTER_LABEL,
                count=mpp_template_filter_count,
            )
        )

    for issue_tag in ISSUE_TAG_ORDER:
        count = sum(
            1
            for row in rows
            if issue_tag
            in record_issue_tags(
                require_row_github_issue_metadata(
                    as_text(row.get("row_number", ""))
                ).tags
            )
        )
        if count == 0:
            continue
        categories.append(
            FilterCategory(
                filter_id=issue_tag_filter_id(issue_tag),
                label=issue_tag_display_text(issue_tag),
                count=count,
            )
        )
    return categories


def summary_rows_html(categories: list[FilterCategory]) -> str:
    grouped_sections: list[str] = []
    finding_categories = [
        category
        for category in categories
        if not category.filter_id.startswith("issue-tag-")
        and category.filter_id != MPP_TEMPLATE_FILTER_ID
    ]
    grouped_categories = (
        (
            "Aleppo notation",
            finding_categories,
        ),
        (
            "Issue tags",
            [
                category
                for category in categories
                if category.filter_id in SUMMARY_ISSUE_TAG_FILTER_IDS
            ],
        ),
        (
            "MPP",
            [
                category
                for category in categories
                if category.filter_id == MPP_TEMPLATE_FILTER_ID
            ],
        ),
    )
    for group_title, group_categories in grouped_categories:
        if not group_categories:
            continue
        group_rows = "\n".join(
            _summary_row_html(category) for category in group_categories
        )
        grouped_sections.append(_summary_group_html(group_title, group_rows))
    return "\n".join(grouped_sections)


def _summary_row_html(category: FilterCategory) -> str:
    return (
        f'<tr data-filter-id="{escape(category.filter_id)}">'
        f'<td><span class="cat-swatch cat-{escape(category.filter_id)}"></span>{escape(category.label)}</td>'
        f"<td>{category.count}</td></tr>"
    )


def _summary_group_html(group_title: str, rows_html: str) -> str:
    return (
        f'<section class="summary-group"><h2 class="summary-group-title">{escape(group_title)}</h2>'
        f'<table class="summary">{rows_html}</table></section>'
    )
