# Initially generated by GitHub Copilot.
from __future__ import annotations

from collections import Counter
import unicodedata
from difflib import SequenceMatcher

HEBREW_LETTERS = frozenset("אבגדהוזחטיכלמנסעפצקרשתךםןףץ")
MATRES = frozenset("וי")

DAGESH = "\N{HEBREW POINT DAGESH OR MAPIQ}"
HIRIQ = "\N{HEBREW POINT HIRIQ}"
TSERE = "\N{HEBREW POINT TSERE}"
QAMATS = "\N{HEBREW POINT QAMATS}"
QAMATS_QATAN = "\N{HEBREW POINT QAMATS QATAN}"
HOLAM = "\N{HEBREW POINT HOLAM}"
QUBUTS = "\N{HEBREW POINT QUBUTS}"

LETTER_NAMES = {
    "א": "alef",
    "ב": "bet",
    "ג": "gimel",
    "ד": "dalet",
    "ה": "he",
    "ו": "vav",
    "ז": "zayin",
    "ח": "het",
    "ט": "tet",
    "י": "yod",
    "ך": "final-kaf",
    "כ": "kaf",
    "ל": "lamed",
    "ם": "final-mem",
    "מ": "mem",
    "ן": "final-nun",
    "נ": "nun",
    "ס": "samekh",
    "ע": "ayin",
    "ף": "final-pe",
    "פ": "pe",
    "ץ": "final-tsadi",
    "צ": "tsadi",
    "ק": "qof",
    "ר": "resh",
    "ש": "shin",
    "ת": "tav",
}
MARK_NAMES = {
    HIRIQ: "ḥiriq",
    TSERE: "tsere",
    QAMATS: "qamats",
    QAMATS_QATAN: "qamats-qatan",
    HOLAM: "ḥolam",
    QUBUTS: "qubuts",
}
MATER_NAMES = {"ו": "vav", "י": "yod"}
MEANINGFUL_SPELLINGS = frozenset(
    {
        "shuruq",
        "ḥiriq-yod",
        "tsere-yod",
        "qamats-vav",
        "qamats-qatan-vav",
        "ḥolam-vav",
    }
)


def describe_xaser_malei_qere_change(mam_text: str, qere_text: str) -> str | None:
    skeleton_mam = _strip_all_points(mam_text)
    skeleton_qere = _strip_all_points(qere_text)
    if skeleton_mam == skeleton_qere:
        return None

    opcodes = list(
        SequenceMatcher(None, skeleton_mam, skeleton_qere, autojunk=False).get_opcodes()
    )
    if not _is_xaser_malei_opcode_shape(opcodes, skeleton_mam, skeleton_qere):
        return None

    concise_description = _describe_single_transition(mam_text, qere_text, opcodes)
    if concise_description is not None:
        return concise_description

    composite_description = _describe_qubuts_shuruq_hiriq_transition(
        mam_text,
        qere_text,
        opcodes,
    )
    if composite_description is not None:
        return composite_description

    mam_suffixes: list[str] = []
    qere_suffixes: list[str] = []
    mam_positions = _skeleton_positions(mam_text)
    qere_positions = _skeleton_positions(qere_text)
    for tag, mam_start, mam_end, qere_start, qere_end in opcodes:
        if tag == "delete":
            for index in range(mam_start, mam_end):
                suffix = _mater_spelling_suffix(
                    text=mam_text,
                    skeleton_index=index,
                    positions=mam_positions,
                )
                if suffix is None:
                    return None
                mam_suffixes.append(suffix)
        elif tag == "insert":
            for index in range(qere_start, qere_end):
                suffix = _mater_spelling_suffix(
                    text=qere_text,
                    skeleton_index=index,
                    positions=qere_positions,
                )
                if suffix is None:
                    return None
                qere_suffixes.append(suffix)
        elif tag == "replace":
            for index in range(mam_start, mam_end):
                suffix = _mater_spelling_suffix(
                    text=mam_text,
                    skeleton_index=index,
                    positions=mam_positions,
                )
                if suffix is None:
                    return None
                mam_suffixes.append(suffix)
            for index in range(qere_start, qere_end):
                suffix = _mater_spelling_suffix(
                    text=qere_text,
                    skeleton_index=index,
                    positions=qere_positions,
                )
                if suffix is None:
                    return None
                qere_suffixes.append(suffix)

    common_suffixes = Counter(mam_suffixes) & Counter(qere_suffixes)
    mam_remaining = list((Counter(mam_suffixes) - common_suffixes).elements())
    qere_remaining = list((Counter(qere_suffixes) - common_suffixes).elements())

    if qere_remaining:
        if not any(suffix in MEANINGFUL_SPELLINGS for suffix in qere_remaining):
            return None
    elif mam_remaining and not any(
        suffix in MEANINGFUL_SPELLINGS for suffix in mam_remaining
    ):
        return None

    # For the common case of a single spelling swap (e.g. ḥiriq-yod → shuruq),
    # use a single-perspective "replace X with Y" form rather than the
    # two-perspective "MAM uses X; UXLC uses Y" form.
    if len(mam_remaining) == 1 and len(qere_remaining) == 1:
        return f"replace {mam_remaining[0]} spelling with {qere_remaining[0]} spelling"

    descriptions = [f"MAM uses {suffix} spelling" for suffix in mam_remaining]
    descriptions.extend(
        f"UXLC qere uses {suffix} spelling" for suffix in qere_remaining
    )

    return "; ".join(descriptions) if descriptions else None


def reduce_xaser_malei_mark_differences(
    mam_text: str,
    qere_text: str,
) -> tuple[str, str] | None:
    skeleton_mam = _strip_all_points(mam_text)
    skeleton_qere = _strip_all_points(qere_text)
    if skeleton_mam == skeleton_qere:
        return None

    opcodes = list(
        SequenceMatcher(None, skeleton_mam, skeleton_qere, autojunk=False).get_opcodes()
    )
    if not _is_xaser_malei_opcode_shape(opcodes, skeleton_mam, skeleton_qere):
        return None

    reduced_pair = _reduce_single_transition_marks(mam_text, qere_text, opcodes)
    if reduced_pair is not None:
        return reduced_pair

    return _reduce_qubuts_shuruq_hiriq_transition_marks(mam_text, qere_text, opcodes)


def _describe_single_transition(
    mam_text: str,
    qere_text: str,
    opcodes: list[tuple[str, int, int, int, int]],
) -> str | None:
    non_equal_opcodes = [opcode for opcode in opcodes if opcode[0] != "equal"]
    if len(non_equal_opcodes) != 1:
        return None

    tag, mam_start, mam_end, qere_start, qere_end = non_equal_opcodes[0]
    if (
        tag == "insert"
        and qere_end - qere_start == 1
        and mam_start > 0
        and qere_start > 0
    ):
        skeleton_mam = _strip_all_points(mam_text)
        qere_positions = _skeleton_positions(qere_text)
        mam_positions = _skeleton_positions(mam_text)
        new_suffix = _mater_spelling_suffix(
            text=qere_text,
            skeleton_index=qere_start,
            positions=qere_positions,
        )
        if new_suffix is None:
            return None
        old_marks = _combining_marks_after(mam_text, mam_positions[mam_start - 1])
        old_vowel = _primary_vowel_name(old_marks)
        if old_vowel is None:
            return None
        old_vowel_mark = _find_primary_vowel_mark(old_marks)
        previous_letter = skeleton_mam[mam_start - 1]
        # If the old vowel mark appears only once in the word, the position is
        # already unambiguous — no need for "after {letter}".
        if old_vowel_mark is None or mam_text.count(old_vowel_mark) > 1:
            return (
                f"replace {old_vowel} with {new_suffix} after "
                f"{LETTER_NAMES[previous_letter]}"
            )
        return f"replace {old_vowel} with {new_suffix}"
    return None


def _reduce_single_transition_marks(
    mam_text: str,
    qere_text: str,
    opcodes: list[tuple[str, int, int, int, int]],
) -> tuple[str, str] | None:
    non_equal_opcodes = [opcode for opcode in opcodes if opcode[0] != "equal"]
    if len(non_equal_opcodes) != 1:
        return None

    tag, mam_start, mam_end, qere_start, qere_end = non_equal_opcodes[0]
    if (
        tag != "insert"
        or qere_end - qere_start != 1
        or mam_start <= 0
        or qere_start <= 0
    ):
        return None

    mam_positions = _skeleton_positions(mam_text)
    qere_positions = _skeleton_positions(qere_text)
    new_suffix = _mater_spelling_suffix(
        text=qere_text,
        skeleton_index=qere_start,
        positions=qere_positions,
    )
    if new_suffix is None:
        return None

    old_source_index = mam_start - 1
    old_source_pos = mam_positions[old_source_index]
    old_source_marks = _combining_marks_after(mam_text, old_source_pos)
    old_vowel_mark = _find_primary_vowel_mark(old_source_marks)
    if old_vowel_mark is None:
        return None

    new_mater_pos = qere_positions[qere_start]
    new_mater_marks = _combining_marks_after(qere_text, new_mater_pos)
    expected_new_mark = _expected_inserted_mater_mark(
        new_suffix=new_suffix,
        old_vowel_mark=old_vowel_mark,
        new_mater_marks=new_mater_marks,
    )
    if expected_new_mark is None:
        return mam_text, qere_text

    reduced_new = _remove_mark_from_letter_occurrence(
        qere_text,
        qere_text[new_mater_pos],
        _letter_occurrence_at_position(qere_text, new_mater_pos),
        expected_new_mark,
    )
    if reduced_new is None:
        return None

    new_source_pos = qere_positions[qere_start - 1]
    new_source_marks = _combining_marks_after(qere_text, new_source_pos)
    if old_vowel_mark in new_source_marks:
        return mam_text, reduced_new

    reduced_old = _remove_mark_from_letter_occurrence(
        mam_text,
        mam_text[old_source_pos],
        _letter_occurrence_at_position(mam_text, old_source_pos),
        old_vowel_mark,
    )
    if reduced_old is None:
        return None
    return reduced_old, reduced_new


def _describe_qubuts_shuruq_hiriq_transition(
    mam_text: str,
    qere_text: str,
    opcodes: list[tuple[str, int, int, int, int]],
) -> str | None:
    non_equal_opcodes = [opcode for opcode in opcodes if opcode[0] != "equal"]
    if len(non_equal_opcodes) != 1:
        return None

    tag, mam_start, mam_end, qere_start, qere_end = non_equal_opcodes[0]
    if tag != "replace" or mam_end - mam_start != 1 or qere_end - qere_start != 1:
        return None

    skeleton_mam = _strip_all_points(mam_text)
    skeleton_qere = _strip_all_points(qere_text)
    if (
        skeleton_mam[mam_start:mam_end] != "י"
        or skeleton_qere[qere_start:qere_end] != "ו"
    ):
        return None
    if mam_end >= len(skeleton_mam) or qere_end >= len(skeleton_qere):
        return None
    if skeleton_mam[mam_end] != "י" or skeleton_qere[qere_end] != "י":
        return None

    mam_positions = _skeleton_positions(mam_text)
    qere_positions = _skeleton_positions(qere_text)
    replaced_mam_pos = mam_positions[mam_start]
    replaced_qere_pos = qere_positions[qere_start]
    next_mam_pos = mam_positions[mam_end]
    next_qere_pos = qere_positions[qere_end]

    previous_mam_marks = _preceding_letter_marks(mam_text, replaced_mam_pos)
    replaced_mam_marks = _combining_marks_after(mam_text, replaced_mam_pos)
    replaced_qere_marks = _combining_marks_after(qere_text, replaced_qere_pos)
    next_mam_marks = _combining_marks_after(mam_text, next_mam_pos)
    next_qere_marks = _combining_marks_after(qere_text, next_qere_pos)

    if QUBUTS not in previous_mam_marks:
        return None
    if HIRIQ not in replaced_mam_marks:
        return None
    if DAGESH not in replaced_qere_marks:
        return None
    if HIRIQ in next_mam_marks:
        return None
    if HIRIQ not in next_qere_marks:
        return None

    return "replace qubuts with shuruq; replace ḥiriq-yod with ḥiriq"


def _reduce_qubuts_shuruq_hiriq_transition_marks(
    mam_text: str,
    qere_text: str,
    opcodes: list[tuple[str, int, int, int, int]],
) -> tuple[str, str] | None:
    non_equal_opcodes = [opcode for opcode in opcodes if opcode[0] != "equal"]
    if len(non_equal_opcodes) != 1:
        return None

    tag, mam_start, mam_end, qere_start, qere_end = non_equal_opcodes[0]
    if tag != "replace" or mam_end - mam_start != 1 or qere_end - qere_start != 1:
        return None

    skeleton_mam = _strip_all_points(mam_text)
    skeleton_qere = _strip_all_points(qere_text)
    if (
        skeleton_mam[mam_start:mam_end] != "י"
        or skeleton_qere[qere_start:qere_end] != "ו"
    ):
        return None
    if mam_end >= len(skeleton_mam) or qere_end >= len(skeleton_qere):
        return None
    if skeleton_mam[mam_end] != "י" or skeleton_qere[qere_end] != "י":
        return None

    mam_positions = _skeleton_positions(mam_text)
    qere_positions = _skeleton_positions(qere_text)
    previous_mam_pos = mam_positions[mam_start - 1]
    replaced_mam_pos = mam_positions[mam_start]
    replaced_qere_pos = qere_positions[qere_start]
    next_qere_pos = qere_positions[qere_end]

    reduced_old = _remove_mark_from_letter_occurrence(
        mam_text,
        mam_text[previous_mam_pos],
        _letter_occurrence_at_position(mam_text, previous_mam_pos),
        QUBUTS,
    )
    if reduced_old is None:
        return None
    reduced_old = _remove_mark_from_letter_occurrence(
        reduced_old,
        mam_text[replaced_mam_pos],
        _letter_occurrence_at_position(mam_text, replaced_mam_pos),
        HIRIQ,
    )
    if reduced_old is None:
        return None

    reduced_new = _remove_mark_from_letter_occurrence(
        qere_text,
        qere_text[replaced_qere_pos],
        _letter_occurrence_at_position(qere_text, replaced_qere_pos),
        DAGESH,
    )
    if reduced_new is None:
        return None
    reduced_new = _remove_mark_from_letter_occurrence(
        reduced_new,
        qere_text[next_qere_pos],
        _letter_occurrence_at_position(qere_text, next_qere_pos),
        HIRIQ,
    )
    if reduced_new is None:
        return None

    return reduced_old, reduced_new


def _is_xaser_malei_opcode_shape(
    opcodes: list[tuple[str, int, int, int, int]],
    skeleton_mam: str,
    skeleton_qere: str,
) -> bool:
    deleted_matres: list[str] = []
    inserted_matres: list[str] = []
    for tag, mam_start, mam_end, qere_start, qere_end in opcodes:
        if tag == "equal":
            continue
        if tag == "delete":
            deleted = skeleton_mam[mam_start:mam_end]
            if not deleted or not all(character in MATRES for character in deleted):
                return False
            deleted_matres.extend(deleted)
            continue
        if tag == "insert":
            inserted = skeleton_qere[qere_start:qere_end]
            if not inserted or not all(character in MATRES for character in inserted):
                return False
            inserted_matres.extend(inserted)
            continue
        if tag == "replace":
            deleted = skeleton_mam[mam_start:mam_end]
            inserted = skeleton_qere[qere_start:qere_end]
            if (
                not deleted
                or not inserted
                or not all(character in MATRES for character in deleted)
                or not all(character in MATRES for character in inserted)
            ):
                return False
            deleted_matres.extend(deleted)
            inserted_matres.extend(inserted)
            continue
        return False
    return sorted(deleted_matres) != sorted(inserted_matres)


def _skeleton_positions(text: str) -> list[int]:
    return [
        index
        for index, character in enumerate(text)
        if not unicodedata.combining(character)
    ]


def _strip_all_points(text: str) -> str:
    return "".join(
        character for character in text if not unicodedata.combining(character)
    )


def _combining_marks_after(text: str, position: int) -> list[str]:
    marks: list[str] = []
    for index in range(position + 1, len(text)):
        character = text[index]
        if not unicodedata.combining(character):
            break
        marks.append(character)
    return marks


def _letter_occurrence_at_position(text: str, position: int) -> int:
    letter = text[position]
    count = 0
    for index, character in enumerate(text):
        if character != letter:
            continue
        count += 1
        if index == position:
            return count
    raise ValueError(f"Could not determine occurrence for {letter!r} at {position}")


def _remove_mark_from_letter_occurrence(
    text: str,
    letter: str,
    occurrence: int,
    mark: str,
) -> str | None:
    letter_count = 0
    for index, character in enumerate(text):
        if character != letter:
            continue
        letter_count += 1
        if letter_count != occurrence:
            continue
        end = index + 1
        while end < len(text) and unicodedata.combining(text[end]):
            if text[end] == mark:
                return text[:end] + text[end + 1 :]
            end += 1
        return None
    return None


def _preceding_letter_marks(text: str, position: int) -> list[str]:
    for index in range(position - 1, -1, -1):
        if text[index] in HEBREW_LETTERS:
            return _combining_marks_after(text, index)
    return []


def _expected_inserted_mater_mark(
    *,
    new_suffix: str,
    old_vowel_mark: str,
    new_mater_marks: list[str],
) -> str | None:
    if new_suffix == "shuruq" and DAGESH in new_mater_marks:
        return DAGESH
    if old_vowel_mark in new_mater_marks:
        return old_vowel_mark
    return None


def _primary_vowel_name(marks: list[str]) -> str | None:
    for mark in marks:
        name = MARK_NAMES.get(mark)
        if name is not None:
            return name
    return None


def _find_primary_vowel_mark(marks: list[str]) -> str | None:
    for mark in marks:
        if mark in MARK_NAMES:
            return mark
    return None


def _mater_spelling_suffix(
    *, text: str, skeleton_index: int, positions: list[int]
) -> str | None:
    character = text[positions[skeleton_index]]
    if character not in MATRES:
        return None
    marks = _combining_marks_after(text, positions[skeleton_index])
    previous_marks = _preceding_letter_marks(text, positions[skeleton_index])
    vowel_name = _vowel_name_for_mater(character, marks, previous_marks)
    if vowel_name is None:
        return MATER_NAMES[character]
    if vowel_name == "shuruq":
        return vowel_name
    return f"{vowel_name}-{MATER_NAMES[character]}"


def _vowel_name_for_mater(
    character: str, marks: list[str], previous_marks: list[str]
) -> str | None:
    if character == "ו":
        if HOLAM in marks:
            return MARK_NAMES[HOLAM]
        if DAGESH in marks:
            return "shuruq"
        if QAMATS in previous_marks:
            return MARK_NAMES[QAMATS]
        if QAMATS_QATAN in previous_marks:
            return MARK_NAMES[QAMATS_QATAN]
        return None
    if character == "י":
        if HIRIQ in marks:
            return MARK_NAMES[HIRIQ]
        if TSERE in marks:
            return MARK_NAMES[TSERE]
        if TSERE in previous_marks:
            return MARK_NAMES[TSERE]
        if HIRIQ in previous_marks:
            return MARK_NAMES[HIRIQ]
        if QAMATS in previous_marks:
            return MARK_NAMES[QAMATS]
        return None
    return None
