# Initially generated by GitHub Copilot.
from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Mapping
import unicodedata

from python_modules.qere_projection import strip_accents_and_meteg

HEBREW_LETTER_PATTERN = re.compile(r"[\u05D0-\u05EA]+")
HEBREW_PUNCTUATION_PATTERN = re.compile(r"[\u05BE\u05C0\u05C3]")
HEBREW_POINT_PATTERN = r"[\u05B0-\u05BC\u05C1\u05C2\u05C7]"
FINAL_HOLAM_HE_PATTERN = re.compile(
    rf"[\u05D0-\u05EA]{HEBREW_POINT_PATTERN}*\u05B9{HEBREW_POINT_PATTERN}*ה$"
)
HOLAM_HE_KETIV_ENDING = "ֹה"
HOLAM_HE_QERE_ENDING = "וֹ"


@dataclass(frozen=True)
class HolamHeEvaluation:
    matches: bool
    reason: str | None
    row_number: str
    verse: str
    word: str
    ketiv: str | None
    qere: str | None
    expected_qere: str | None


def evaluate_holam_he_row(row: Mapping[str, object]) -> HolamHeEvaluation:
    row_number = _as_text(row.get("row_number", ""))
    verse = _as_text(row.get("verse", ""))
    word = _as_text(row.get("word", ""))
    notes_uxlc = _as_text(row.get("notes-UXLC", ""))
    notes_tokens = notes_uxlc.split()
    if len(notes_tokens) != 2:
        return HolamHeEvaluation(
            matches=False,
            reason=(
                f"row {row_number} {verse} must have exactly 2 UXLC note tokens, "
                f"got {notes_tokens!r}"
            ),
            row_number=row_number,
            verse=verse,
            word=word,
            ketiv=None,
            qere=None,
            expected_qere=None,
        )

    ketiv, qere = notes_tokens
    expected_qere = expected_holam_he_qere(word)
    if expected_qere is None:
        return HolamHeEvaluation(
            matches=False,
            reason=(f"row {row_number} {verse} has no final he in MAM word {word!r}"),
            row_number=row_number,
            verse=verse,
            word=word,
            ketiv=ketiv,
            qere=qere,
            expected_qere=None,
        )

    if hebrew_letters_only(word) != hebrew_letters_only(ketiv):
        return HolamHeEvaluation(
            matches=False,
            reason=(
                f"row {row_number} {verse} violates ketiv-letter match: "
                f"MAM {word!r}, UXLC ketiv {ketiv!r}"
            ),
            row_number=row_number,
            verse=verse,
            word=word,
            ketiv=ketiv,
            qere=qere,
            expected_qere=expected_qere,
        )

    ketiv_core = _normalize_hebrew_form(
        HEBREW_PUNCTUATION_PATTERN.sub("", strip_accents_and_meteg(word))
    )
    if not FINAL_HOLAM_HE_PATTERN.search(ketiv_core):
        return HolamHeEvaluation(
            matches=False,
            reason=(
                f"row {row_number} {verse} must end with {HOLAM_HE_KETIV_ENDING!r} "
                f"in the ketiv after accent stripping, got {ketiv_core!r}"
            ),
            row_number=row_number,
            verse=verse,
            word=word,
            ketiv=ketiv,
            qere=qere,
            expected_qere=expected_qere,
        )

    if hebrew_letters_only(qere) != hebrew_letters_only(expected_qere):
        return HolamHeEvaluation(
            matches=False,
            reason=(
                f"row {row_number} {verse} violates expected qere letters: "
                f"expected {expected_qere!r}, got {qere!r}"
            ),
            row_number=row_number,
            verse=verse,
            word=word,
            ketiv=ketiv,
            qere=qere,
            expected_qere=expected_qere,
        )

    qere_core_with_punctuation = _normalize_hebrew_form(strip_accents_and_meteg(qere))
    qere_core = _normalize_hebrew_form(
        HEBREW_PUNCTUATION_PATTERN.sub("", qere_core_with_punctuation)
    )
    if not qere_core.endswith(HOLAM_HE_QERE_ENDING):
        return HolamHeEvaluation(
            matches=False,
            reason=(
                f"row {row_number} {verse} must end with {HOLAM_HE_QERE_ENDING!r} "
                f"in the qere after accent stripping, got {qere_core!r}"
            ),
            row_number=row_number,
            verse=verse,
            word=word,
            ketiv=ketiv,
            qere=qere,
            expected_qere=expected_qere,
        )

    return HolamHeEvaluation(
        matches=True,
        reason=None,
        row_number=row_number,
        verse=verse,
        word=word,
        ketiv=ketiv,
        qere=qere,
        expected_qere=expected_qere,
    )


def require_holam_he_row_match(row: Mapping[str, object], *, context: str) -> None:
    evaluation = evaluate_holam_he_row(row)
    if evaluation.matches:
        return
    raise ValueError(f"{evaluation.reason} ({context})")


def expected_holam_he_qere(word: str) -> str | None:
    last_he_index = word.rfind("ה")
    if last_he_index == -1:
        return None
    return f"{word[:last_he_index]}ו{word[last_he_index + 1:]}"


def hebrew_letters_only(text: str) -> str:
    return "".join(HEBREW_LETTER_PATTERN.findall(text))


def _as_text(value: object) -> str:
    return value if isinstance(value, str) else str(value)


def _normalize_hebrew_form(text: str) -> str:
    return unicodedata.normalize("NFC", text)
