# Initially generated by GitHub Copilot.
from __future__ import annotations

import json
from pathlib import Path
import subprocess

from python_modules.json_io import write_json
from python_modules.table_row_github_issues import (
    ISSUE_LABEL_TO_TAG,
    ISSUE_TAG_DISPLAY_TEXT,
    REPO_NAME,
    REPO_OWNER,
    ROW_GITHUB_ISSUES_JSON_PATH,
    RowGitHubIssueMetadata,
    load_row_github_issues,
    reload_row_github_issues,
)

GITHUB_ISSUE_LIST_LIMIT = 500


def refresh_row_github_issue_metadata(
    json_path: Path = ROW_GITHUB_ISSUES_JSON_PATH,
) -> Path:
    existing_rows = load_row_github_issues(json_path)
    issue_numbers = {metadata.issue_number for metadata in existing_rows.values()}
    live_issues = fetch_live_github_issues(issue_numbers=issue_numbers)
    refreshed_rows = build_refreshed_row_github_issues(
        existing_rows=existing_rows,
        live_issues=live_issues,
    )
    write_json(json_path, row_github_issues_payload(refreshed_rows))
    if json_path == ROW_GITHUB_ISSUES_JSON_PATH:
        reload_row_github_issues(json_path)
    return json_path


def fetch_live_github_issues(
    *, issue_numbers: set[int]
) -> dict[int, dict[str, object]]:
    result = subprocess.run(
        [
            "gh",
            "issue",
            "list",
            "--repo",
            f"{REPO_OWNER}/{REPO_NAME}",
            "--state",
            "all",
            "--limit",
            str(max(GITHUB_ISSUE_LIST_LIMIT, len(issue_numbers))),
            "--json",
            "number,state,labels",
        ],
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
    issues = json.loads(result.stdout)
    live_issues = {int(issue["number"]): issue for issue in issues}
    missing_issue_numbers = sorted(issue_numbers.difference(live_issues))
    if missing_issue_numbers:
        raise KeyError(f"missing live GitHub issues: {missing_issue_numbers}")
    return live_issues


def build_refreshed_row_github_issues(
    *,
    existing_rows: dict[str, RowGitHubIssueMetadata],
    live_issues: dict[int, dict[str, object]],
) -> dict[str, RowGitHubIssueMetadata]:
    refreshed_rows: dict[str, RowGitHubIssueMetadata] = {}
    for row_number in sorted(existing_rows, key=int):
        current_metadata = existing_rows[row_number]
        issue = live_issues[current_metadata.issue_number]
        labels = issue.get("labels")
        if not isinstance(labels, list):
            raise ValueError(
                f"live GitHub issue {current_metadata.issue_number} labels must be a list"
            )
        label_names = []
        for label in labels:
            if not isinstance(label, dict):
                raise ValueError(
                    f"live GitHub issue {current_metadata.issue_number} labels must contain only objects"
                )
            label_name = label.get("name")
            if not isinstance(label_name, str):
                raise ValueError(
                    f"live GitHub issue {current_metadata.issue_number} label names must be strings"
                )
            label_names.append(label_name)
        state = issue.get("state")
        if not isinstance(state, str):
            raise ValueError(
                f"live GitHub issue {current_metadata.issue_number} state must be a string"
            )
        refreshed_rows[row_number] = RowGitHubIssueMetadata(
            issue_number=current_metadata.issue_number,
            is_closed=state.upper() == "CLOSED",
            tags=normalize_issue_tags(label_names),
        )
    return refreshed_rows


def normalize_issue_tags(label_names: list[str]) -> tuple[str, ...]:
    normalized_tags = {
        ISSUE_LABEL_TO_TAG[label_name]
        for label_name in label_names
        if label_name in ISSUE_LABEL_TO_TAG
    }
    return tuple(tag for tag in ISSUE_TAG_DISPLAY_TEXT if tag in normalized_tags)


def row_github_issues_payload(
    rows: dict[str, RowGitHubIssueMetadata],
) -> dict[str, dict[str, object]]:
    return {
        row_number: {
            "issue_number": metadata.issue_number,
            "is_closed": metadata.is_closed,
            "tags": list(metadata.tags),
        }
        for row_number, metadata in sorted(rows.items(), key=lambda item: int(item[0]))
    }
