# Initially generated by GitHub Copilot.
from __future__ import annotations

import json
from pathlib import Path
import subprocess

from python_modules.table_row_github_issues import (
    ISSUE_LABEL_TO_TAG,
    ISSUE_TAG_DISPLAY_TEXT,
    REPO_NAME,
    REPO_OWNER,
    ROW_GITHUB_ISSUES,
    RowGitHubIssueMetadata,
)

TABLE_ROW_GITHUB_ISSUES_MODULE_PATH = (
    Path(__file__).resolve().with_name("table_row_github_issues.py")
)
GITHUB_ISSUE_LIST_LIMIT = 500


def refresh_row_github_issue_metadata(
    module_path: Path = TABLE_ROW_GITHUB_ISSUES_MODULE_PATH,
) -> Path:
    issue_numbers = {metadata.issue_number for metadata in ROW_GITHUB_ISSUES.values()}
    live_issues = fetch_live_github_issues(issue_numbers=issue_numbers)
    refreshed_rows = build_refreshed_row_github_issues(
        existing_rows=ROW_GITHUB_ISSUES,
        live_issues=live_issues,
    )
    module_text = render_table_row_github_issues_module_text(refreshed_rows)
    module_path.write_text(module_text, encoding="utf-8")
    return module_path


def fetch_live_github_issues(
    *, issue_numbers: set[int]
) -> dict[int, dict[str, object]]:
    result = subprocess.run(
        [
            "gh",
            "issue",
            "list",
            "--repo",
            f"{REPO_OWNER}/{REPO_NAME}",
            "--state",
            "all",
            "--limit",
            str(max(GITHUB_ISSUE_LIST_LIMIT, len(issue_numbers))),
            "--json",
            "number,state,labels",
        ],
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
    issues = json.loads(result.stdout)
    live_issues = {int(issue["number"]): issue for issue in issues}
    missing_issue_numbers = sorted(issue_numbers.difference(live_issues))
    if missing_issue_numbers:
        raise KeyError(f"missing live GitHub issues: {missing_issue_numbers}")
    return live_issues


def build_refreshed_row_github_issues(
    *,
    existing_rows: dict[str, RowGitHubIssueMetadata],
    live_issues: dict[int, dict[str, object]],
) -> dict[str, RowGitHubIssueMetadata]:
    refreshed_rows: dict[str, RowGitHubIssueMetadata] = {}
    for row_number in sorted(existing_rows, key=int):
        current_metadata = existing_rows[row_number]
        issue = live_issues[current_metadata.issue_number]
        labels = issue.get("labels")
        if not isinstance(labels, list):
            raise ValueError(
                f"live GitHub issue {current_metadata.issue_number} labels must be a list"
            )
        label_names = []
        for label in labels:
            if not isinstance(label, dict):
                raise ValueError(
                    f"live GitHub issue {current_metadata.issue_number} labels must contain only objects"
                )
            label_name = label.get("name")
            if not isinstance(label_name, str):
                raise ValueError(
                    f"live GitHub issue {current_metadata.issue_number} label names must be strings"
                )
            label_names.append(label_name)
        state = issue.get("state")
        if not isinstance(state, str):
            raise ValueError(
                f"live GitHub issue {current_metadata.issue_number} state must be a string"
            )
        refreshed_rows[row_number] = RowGitHubIssueMetadata(
            issue_number=current_metadata.issue_number,
            is_closed=state.upper() == "CLOSED",
            tags=normalize_issue_tags(label_names),
        )
    return refreshed_rows


def normalize_issue_tags(label_names: list[str]) -> tuple[str, ...]:
    normalized_tags = {
        ISSUE_LABEL_TO_TAG[label_name]
        for label_name in label_names
        if label_name in ISSUE_LABEL_TO_TAG
    }
    return tuple(tag for tag in ISSUE_TAG_DISPLAY_TEXT if tag in normalized_tags)


def render_table_row_github_issues_module_text(
    rows: dict[str, RowGitHubIssueMetadata],
) -> str:
    label_lines = "\n".join(
        f"    {label!r}: {tag!r}," for label, tag in ISSUE_LABEL_TO_TAG.items()
    )
    display_lines = "\n".join(
        f"    {tag!r}: {display_text!r},"
        for tag, display_text in ISSUE_TAG_DISPLAY_TEXT.items()
    )
    row_lines = "\n".join(
        f"    {row_number!r}: RowGitHubIssueMetadata(issue_number={metadata.issue_number}, is_closed={metadata.is_closed}, tags={metadata.tags!r}),"
        for row_number, metadata in sorted(rows.items(), key=lambda item: int(item[0]))
    )
    return (
        "from __future__ import annotations\n\n"
        "from dataclasses import dataclass\n"
        "from typing import Final\n\n"
        f"REPO_OWNER: Final = {REPO_OWNER!r}\n"
        f"REPO_NAME: Final = {REPO_NAME!r}\n\n"
        "ISSUE_LABEL_TO_TAG: Final[dict[str, str]] = {\n"
        f"{label_lines}\n"
        "}\n\n"
        "ISSUE_TAG_DISPLAY_TEXT: Final[dict[str, str]] = {\n"
        f"{display_lines}\n"
        "}\n\n"
        "\n"
        "@dataclass(frozen=True)\n"
        "class RowGitHubIssueMetadata:\n"
        "    issue_number: int\n"
        "    is_closed: bool\n"
        "    tags: tuple[str, ...] = ()\n\n"
        "\n"
        "ROW_GITHUB_ISSUES: dict[str, RowGitHubIssueMetadata] = {\n"
        f"{row_lines}\n"
        "}\n\n"
        "\n"
        "def issue_url_from_number(issue_number: int) -> str:\n"
        '    return f"https://github.com/{REPO_OWNER}/{REPO_NAME}/issues/{issue_number}"\n\n'
        "\n"
        "def row_github_issue_metadata(row_number: str) -> RowGitHubIssueMetadata | None:\n"
        "    return ROW_GITHUB_ISSUES.get(str(row_number))\n\n"
        "\n"
        "def require_row_github_issue_metadata(row_number: str) -> RowGitHubIssueMetadata:\n"
        "    metadata = row_github_issue_metadata(row_number)\n"
        "    if metadata is None:\n"
        '        raise KeyError(f"missing GitHub issue metadata for table row {row_number}")\n'
        "    return metadata\n\n"
        "\n"
        "def row_github_issue_number(row_number: str) -> int | None:\n"
        "    metadata = row_github_issue_metadata(row_number)\n"
        "    if metadata is None:\n"
        "        return None\n"
        "    return metadata.issue_number\n\n"
        "\n"
        "def row_github_issue_url(row_number: str) -> str | None:\n"
        "    issue_number = row_github_issue_number(row_number)\n"
        "    if issue_number is None:\n"
        "        return None\n"
        "    return issue_url_from_number(issue_number)\n\n"
        "\n"
        "def row_github_issue_is_closed(row_number: str) -> bool | None:\n"
        "    metadata = row_github_issue_metadata(row_number)\n"
        "    if metadata is None:\n"
        "        return None\n"
        "    return metadata.is_closed\n\n"
        "\n"
        "def row_github_issue_tags(row_number: str) -> tuple[str, ...]:\n"
        "    metadata = row_github_issue_metadata(row_number)\n"
        "    if metadata is None:\n"
        "        return ()\n"
        "    return metadata.tags\n"
    )
