# Initially generated by GitHub Copilot.
from __future__ import annotations

from pathlib import Path

PALETTE = [
    "#1f5f8b",
    "#2e8b57",
    "#a2472f",
    "#6a4c93",
    "#7a5f00",
    "#3e6b7f",
    "#8b3a62",
    "#4f6d2e",
    "#505c91",
    "#9c4a22",
]

ASSETS_DIR = Path(__file__).resolve().parent / "assets"
CSS_TEMPLATE_PATH = ASSETS_DIR / "table_data_findings.css"
JS_TEMPLATE_PATH = ASSETS_DIR / "table_data_findings.js"
CSS_COLOR_PLACEHOLDER = "/* __FINDING_COLORS__ */"


def write_report_assets(
    css_output_path: Path,
    js_output_path: Path,
    finding_ids: list[str],
) -> None:
    color_rules = "\n".join(
        f".cat-{finding_id} {{ background: {PALETTE[idx % len(PALETTE)]}; }}"
        for idx, finding_id in enumerate(finding_ids)
    )

    css_template = CSS_TEMPLATE_PATH.read_text(encoding="utf-8")
    css_text = css_template.replace(CSS_COLOR_PLACEHOLDER, color_rules)
    js_text = JS_TEMPLATE_PATH.read_text(encoding="utf-8")

    css_output_path.parent.mkdir(parents=True, exist_ok=True)
    js_output_path.parent.mkdir(parents=True, exist_ok=True)
    css_output_path.write_text(css_text, encoding="utf-8")
    js_output_path.write_text(js_text, encoding="utf-8")
