# Initially generated by GitHub Copilot.
from __future__ import annotations

from python_modules.qere_projection import qere_arg_key_for_template

SUPPORTED_QERE_DOC_PREFIXES = ("א-קרי=", "ל-קרי=")


def supported_qere_wrapper_from_template_args(
    template_args: list[dict[str, str]],
) -> dict[str, str] | None:
    """Return the unique supported-qere wrapper in template_args, or None if ambiguous."""
    candidates: list[tuple[str, str, str]] = []
    for index in range(len(template_args)):
        candidate = _supported_qere_wrapper_candidate_from_index(template_args, index)
        if candidate is None or candidate in candidates:
            continue
        candidates.append(candidate)

    if len(candidates) != 1:
        return None

    template_name, ketiv, qere = candidates[0]
    return {
        "template_name": template_name,
        "ketiv": ketiv,
        "qere": qere,
    }


def supported_qere_wrapper_for_matching_args(
    matching_args: list[dict[str, str]],
    all_args: list[dict[str, str]],
) -> dict[str, str] | None:
    """
    Return the unique supported-qere wrapper identified by the matching template args.

    Unlike supported_qere_wrapper_from_template_args, this searches only the wrappers
    whose ketiv (or qere) appears in matching_args, so it works correctly even when the
    verse contains multiple wrappers.
    """
    candidates: list[tuple[str, str, str]] = []
    for match in matching_args:
        for index, arg in enumerate(all_args):
            if arg != match:
                continue
            candidate = _supported_qere_wrapper_candidate_from_index(all_args, index)
            if candidate is None or candidate in candidates:
                continue
            candidates.append(candidate)

    if len(candidates) != 1:
        return None

    template_name, ketiv, qere = candidates[0]
    return {
        "template_name": template_name,
        "ketiv": ketiv,
        "qere": qere,
    }


def _supported_qere_wrapper_candidate_from_index(
    template_args: list[dict[str, str]],
    index: int,
) -> tuple[str, str, str] | None:
    current = template_args[index]
    template_name = current.get("template_name")
    argument_key = current.get("argument_key")
    argument_text = current.get("argument_text")
    if template_name is None or argument_key not in {"1", "2"} or argument_text is None:
        return None

    qere_key = qere_arg_key_for_template(template_name)
    if qere_key is None:
        return None

    partner_index = index + 1 if argument_key == "1" else index - 1
    if partner_index < 0 or partner_index >= len(template_args):
        return None

    partner = template_args[partner_index]
    if partner.get("template_name") != template_name:
        return None

    partner_key = partner.get("argument_key")
    partner_text = partner.get("argument_text")
    if partner_key not in {"1", "2"} or partner_text is None:
        return None

    expected_partner_key = "2" if argument_key == "1" else "1"
    if partner_key != expected_partner_key:
        return None

    args_by_key = {
        argument_key: argument_text,
        partner_key: partner_text,
    }
    if set(args_by_key) != {"1", "2"}:
        return None

    if template_name == 'קו"כ-אם':
        qere = _strip_supported_qere_doc(args_by_key["2"])
        if qere is None:
            return None
        return template_name, args_by_key["1"], qere

    if template_name == "קרי ולא כתיב":
        return template_name, args_by_key["1"], args_by_key["2"]

    if template_name == "כתיב ולא קרי":
        return None

    if 'כו"ק' in template_name or 'קו"כ' in template_name:
        return template_name, args_by_key["1"], args_by_key["2"]

    return None


def _strip_supported_qere_doc(text: str) -> str | None:
    for prefix in SUPPORTED_QERE_DOC_PREFIXES:
        if text.startswith(prefix):
            return text[len(prefix) :]
    return None
