# Initially generated by GitHub Copilot.
from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from xml.etree import ElementTree as ET

from python_modules.extract_docx_notes import INVISIBLE_MARK_PATTERN
from python_modules.json_io import load_json
from python_modules.verify_table_words_in_mam_plus import (
    parse_table_verse,
    standard_book_name_by_abbreviation,
    standard_book_name_for_table_verse,
)

MAQAF = "\u05be"
WORD_LIKE_TAGS = frozenset({"w", "k", "q"})
KNOWN_UXLC_BUGGY_QERE_BY_VERSE = {
    "Joshua 10:24.19": ("הֶהָלְכ֣וּ", "הֶהָלְכ֣וְּּ"),
}
UXLC_XML_BASENAME_BY_BOOK = {
    "Genesis": "Genesis",
    "Exodus": "Exodus",
    "Leviticus": "Leviticus",
    "Numbers": "Numbers",
    "Deuteronomy": "Deuteronomy",
    "Joshua": "Joshua",
    "Judges": "Judges",
    "1Samuel": "Samuel_1",
    "2Samuel": "Samuel_2",
    "1Kings": "Kings_1",
    "2Kings": "Kings_2",
    "Isaiah": "Isaiah",
    "Jeremiah": "Jeremiah",
    "Ezekiel": "Ezekiel",
    "Hosea": "Hosea",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obadiah",
    "Jonah": "Jonah",
    "Micah": "Micah",
    "Nahum": "Nahum",
    "Habakkuk": "Habakkuk",
    "Tsefaniah": "Zephaniah",
    "Haggai": "Haggai",
    "Zechariah": "Zechariah",
    "Malachi": "Malachi",
    "Psalms": "Psalms",
    "Proverbs": "Proverbs",
    "Job": "Job",
    "SongOfSongs": "Song_of_Songs",
    "Ruth": "Ruth",
    "Lamentations": "Lamentations",
    "Ecclesiastes": "Ecclesiastes",
    "Esther": "Esther",
    "Daniel": "Daniel",
    "Ezra": "Ezra",
    "Nehemiah": "Nehemiah",
    "1Chronicles": "Chronicles_1",
    "2Chronicles": "Chronicles_2",
}


@dataclass(frozen=True)
class VerseToken:
    text: str
    source_tags: tuple[str, ...]
    source_indices: tuple[int, ...]


def verify_table_notes_in_uxlc(
    table_json_path: Path,
    uxlc_utils_path: Path,
) -> dict[str, object]:
    table_data = load_json(table_json_path)
    if not isinstance(table_data, dict):
        raise ValueError("table JSON root must be an object")

    table = table_data.get("table")
    if not isinstance(table, dict):
        raise ValueError("table JSON missing object key 'table'")

    rows = table.get("rows")
    if not isinstance(rows, list):
        raise ValueError("table JSON missing list key 'rows'")

    std_book_name_by_abbrev = standard_book_name_by_abbreviation(table)

    row_reports: list[dict[str, object]] = []
    missing_rows: list[dict[str, object]] = []

    for row in rows:
        if not isinstance(row, dict):
            raise ValueError(f"row must be object, got: {type(row)}")

        row_number = row.get("row_number")
        verse = row.get("verse")
        notes_uxlc = row.get("notes-UXLC")

        if not isinstance(row_number, int):
            raise ValueError(f"row has invalid row_number: {row!r}")
        if not isinstance(verse, str):
            raise ValueError(f"row has invalid verse at row {row_number}")
        if not isinstance(notes_uxlc, str):
            raise ValueError(f"row has invalid notes-UXLC at row {row_number}")

        notes_tokens = notes_uxlc.split()
        if len(notes_tokens) != 2:
            raise ValueError(
                f"expected exactly 2 UXLC note tokens at row {row_number}, got {notes_tokens!r}"
            )
        ketiv_claim, qere_claim = (
            _normalized_uxlc_text(notes_tokens[0]),
            _normalized_uxlc_text(notes_tokens[1]),
        )

        book_token, chapter_num, verse_num = parse_table_verse(verse)
        std_book_name = standard_book_name_for_table_verse(
            book_token=book_token,
            std_book_name_by_abbrev=std_book_name_by_abbrev,
            row_number=row_number,
        )
        verse_tokens = uxlc_verse_tokens(
            uxlc_utils_path=uxlc_utils_path,
            std_book_name=std_book_name,
            chapter_num=chapter_num,
            verse_num=verse_num,
        )

        ketiv_match = _find_claim_match(verse_tokens, ketiv_claim, required_tag="k")
        qere_match = _find_claim_match(verse_tokens, qere_claim, required_tag="q")
        qere_match_known_bug = False
        if qere_match is None:
            qere_match = _find_known_bug_qere_match(
                verse=verse,
                verse_tokens=verse_tokens,
                qere_claim=qere_claim,
            )
            qere_match_known_bug = qere_match is not None

        report_row = {
            "row_number": row_number,
            "verse": verse,
            "notes_uxlc": notes_uxlc,
            "ketiv_claim": ketiv_claim,
            "qere_claim": qere_claim,
            "uxlc_file_for_verse": _uxlc_xml_path(
                uxlc_utils_path=uxlc_utils_path,
                std_book_name=std_book_name,
            ).name,
            "uxlc_verse_tokens": [token.text for token in verse_tokens],
            "found_ketiv_claim_in_uxlc": ketiv_match is not None,
            "found_qere_claim_in_uxlc": qere_match is not None,
            "found_qere_claim_via_known_uxlc_bug": qere_match_known_bug,
            "ketiv_match_source_tags": (
                [] if ketiv_match is None else list(ketiv_match.source_tags)
            ),
            "ketiv_match_source_indices": (
                [] if ketiv_match is None else list(ketiv_match.source_indices)
            ),
            "qere_match_source_tags": (
                [] if qere_match is None else list(qere_match.source_tags)
            ),
            "qere_match_source_indices": (
                [] if qere_match is None else list(qere_match.source_indices)
            ),
        }
        row_reports.append(report_row)

        if ketiv_match is None or qere_match is None:
            missing_rows.append(report_row)

    summary = {
        "row_count": len(rows),
        "rows_missing_claim_count": len(missing_rows),
        "rows_missing_ketiv_claim_count": sum(
            1 for row in missing_rows if not row["found_ketiv_claim_in_uxlc"]
        ),
        "rows_missing_qere_claim_count": sum(
            1 for row in missing_rows if not row["found_qere_claim_in_uxlc"]
        ),
    }

    return {
        "summary": summary,
        "rows": row_reports,
        "rows_missing_claims": missing_rows,
    }


def _find_claim_match(
    verse_tokens: list[VerseToken],
    claim: str,
    required_tag: str,
) -> VerseToken | None:
    for token in verse_tokens:
        if token.text == claim and required_tag in token.source_tags:
            return token
    return None


def _find_known_bug_qere_match(
    verse: str,
    verse_tokens: list[VerseToken],
    qere_claim: str,
) -> VerseToken | None:
    known_bug = KNOWN_UXLC_BUGGY_QERE_BY_VERSE.get(verse)
    if known_bug is None:
        return None

    fixed_qere, buggy_qere = known_bug
    if qere_claim != fixed_qere:
        return None

    return _find_claim_match(verse_tokens, buggy_qere, required_tag="q")


def uxlc_verse_tokens(
    uxlc_utils_path: Path,
    std_book_name: str,
    chapter_num: int,
    verse_num: int,
) -> list[VerseToken]:
    verse = _uxlc_verse_element(
        uxlc_utils_path=uxlc_utils_path,
        std_book_name=std_book_name,
        chapter_num=chapter_num,
        verse_num=verse_num,
    )
    return _merged_uxlc_tokens(verse)


def _merged_uxlc_tokens(verse: ET.Element) -> list[VerseToken]:
    merged_tokens: list[VerseToken] = []

    for source_index, child in enumerate(verse, start=1):
        if child.tag not in WORD_LIKE_TAGS:
            continue

        text = _uxlc_word_surface_text(child)
        if not text:
            continue

        token = VerseToken(
            text=text,
            source_tags=(child.tag,),
            source_indices=(source_index,),
        )
        if merged_tokens and _should_merge_with_previous(
            previous=merged_tokens[-1], current_tag=child.tag
        ):
            previous = merged_tokens[-1]
            merged_tokens[-1] = VerseToken(
                text=previous.text + token.text,
                source_tags=previous.source_tags + token.source_tags,
                source_indices=previous.source_indices + token.source_indices,
            )
            continue

        merged_tokens.append(token)

    return merged_tokens


def _uxlc_word_surface_text(node: ET.Element) -> str:
    parts = [_stripped_text(node.text)]
    for child in node:
        if child.tag == "s":
            parts.append(_stripped_text(child.text))
        elif child.tag == "x":
            pass
        else:
            raise ValueError(f"unexpected UXLC word child tag: {child.tag!r}")

        parts.append(_stripped_text(child.tail))

    return _normalized_uxlc_text("".join(part for part in parts if part))


def _normalized_uxlc_text(text: str) -> str:
    return INVISIBLE_MARK_PATTERN.sub("", text)


def _should_merge_with_previous(previous: VerseToken, current_tag: str) -> bool:
    if not previous.text.endswith(MAQAF):
        return False

    previous_last_tag = previous.source_tags[-1]
    return current_tag == previous_last_tag or (
        previous_last_tag == "w" and current_tag == "k"
    )


def _stripped_text(value: str | None) -> str:
    return value.strip() if value else ""


def _uxlc_verse_element(
    uxlc_utils_path: Path,
    std_book_name: str,
    chapter_num: int,
    verse_num: int,
) -> ET.Element:
    root = _uxlc_book_root(
        _uxlc_xml_path(uxlc_utils_path=uxlc_utils_path, std_book_name=std_book_name)
    )
    verse = root.find(f".//c[@n='{chapter_num}']/v[@n='{verse_num}']")
    if verse is None:
        raise ValueError(
            "expected verse missing in UXLC data: "
            f"book={std_book_name}, chapter={chapter_num}, verse={verse_num}"
        )
    return verse


@lru_cache(maxsize=64)
def _uxlc_book_root(xml_path: Path) -> ET.Element:
    if not xml_path.exists():
        raise ValueError(f"expected UXLC XML file missing: {xml_path}")
    return ET.parse(xml_path).getroot()


def _uxlc_xml_path(uxlc_utils_path: Path, std_book_name: str) -> Path:
    basename = UXLC_XML_BASENAME_BY_BOOK.get(std_book_name)
    if basename is None:
        raise ValueError(f"unsupported UXLC standard book name: {std_book_name!r}")
    return uxlc_utils_path / "in" / "UXLC-39" / f"{basename}.xml"
