# Initially generated by GitHub Copilot.
"""Roundtrip verification of MPP diff descriptions.

For each diff, extract ChangeOps, apply them to normalize(old), and
assert the result equals normalize(new).  This runs inline during
report generation so incomplete descriptions fail loudly.

Exports:
    verify_all  — verify a list of classified diffs
    verify_diff — verify one diff (raises on failure)
"""

import sys

from pydiff_mpp.change_ops import is_structural_op, is_text_op
from pydiff_mpp.change_ops_apply import (
    _ANY_STRUCTURE,
    apply_structural_ops,
    apply_text_ops,
)
from pydiff_mpp.change_ops_extract import extract_change_ops
from pydiff_mpp.mpp_normalize import normalize_structure, normalize_text
from pydiff_mpp.mpp_structure import (
    _template_name_counter,
    _template_name_multiset_delta,
)


class VerificationError(Exception):
    """A diff description failed the roundtrip check."""

    pass


def _ref(diff):
    return f"{diff['book']} {diff['chapter']}:{diff['verse']}"


def verify_diff(diff):
    """Verify one classified diff.  Raises VerificationError on failure."""
    old_text = diff["old_text"]
    new_text = diff["new_text"]
    old_ep = diff["old_ep"]
    new_ep = diff["new_ep"]
    category = diff["category"]

    ops = extract_change_ops(
        old_text,
        new_text,
        category,
        diff["book"],
        diff["chapter"],
        diff["verse"],
        old_ep,
        new_ep,
    )

    text_ops = [op for op in ops if is_text_op(op)]
    structural_ops = [op for op in ops if is_structural_op(op)]

    # ── Text-level check ─────────────────────────────────────
    if text_ops:
        norm_old = normalize_text(old_text)
        norm_new = normalize_text(new_text)
        reconstructed = apply_text_ops(norm_old, text_ops)
        if reconstructed != norm_new:
            raise VerificationError(
                f"Text roundtrip failed for {_ref(diff)}: "
                f"category={category}, "
                f"ops={text_ops!r}, "
                f"old={old_text!r}, "
                f"new={new_text!r}, "
                f"reconstructed={reconstructed!r}"
            )

    # ── Structural check ─────────────────────────────────────
    old_sig = normalize_structure(old_ep)
    new_sig = normalize_structure(new_ep)
    if old_sig != new_sig:
        if not structural_ops:
            # No structural ops from extract_change_ops.  But commit b5bb715
            # added a separate path: mpp_json/_serialize_diff computes
            # _template_name_multiset_delta for text-changed diffs and
            # surfaces templates_added/templates_removed.  If that delta
            # fully accounts for the structural change, the description
            # is complete.
            added, removed = _template_name_multiset_delta(old_ep, new_ep)
            if not added and not removed:
                # Structure changed but no template names added or removed —
                # a pure restructuring that isn't surfaced anywhere.
                raise VerificationError(
                    f"Unreported structural change for {_ref(diff)}: "
                    f"category={category}, "
                    f"old_sig has {len(old_sig)} entries, "
                    f"new_sig has {len(new_sig)} entries"
                )
            # Delta is non-empty — mpp_json will surface it.  No further
            # roundtrip check needed.
        else:
            old_counter = _template_name_counter(old_ep)
            new_counter = _template_name_counter(new_ep)
            reconstructed = apply_structural_ops(old_counter, structural_ops)
            if reconstructed is not _ANY_STRUCTURE and reconstructed != new_counter:
                raise VerificationError(
                    f"Structural roundtrip failed for {_ref(diff)}: "
                    f"category={category}, "
                    f"ops={structural_ops!r}, "
                    f"expected={dict(new_counter)}, "
                    f"got={dict(reconstructed)}"
                )


def verify_all(diffs, *, quiet=False):
    """Verify all classified diffs.  Returns a list of VerificationErrors.

    Does not raise — collects all failures so the pipeline can report
    them together rather than stopping at the first.
    """
    errors = []
    for diff in diffs:
        try:
            verify_diff(diff)
        except VerificationError as e:
            errors.append(e)
    if errors and not quiet:
        print(
            f"\n{'=' * 60}\n"
            f"VERIFICATION: {len(errors)} diff(s) failed roundtrip check "
            f"out of {len(diffs)} total\n"
            f"{'=' * 60}",
            file=sys.stderr,
        )
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        print(file=sys.stderr)
    return errors
