# Initially generated by GitHub Copilot.
"""Normalize EP structures and text to eliminate known dont-care differences.

This module is the explicit "dont-care registry" — every difference the
verifier should ignore is encoded as a documented transformation here,
rather than scattered implicitly across the pipeline.

Exports:
    normalize_text      — normalize flattened text (currently identity)
    normalize_ep        — deep-copy EP with dont-care fields neutralized
    normalize_structure — normalized EP → structural signature
"""

import copy

from pydiff_mpp.mpp_flatten import (
    _is_qere_velo_ketiv_template,
    _strip_square_brackets,
    _flatten_element,
)
from pydiff_mpp.mpp_param_access import _MISSING, _get_param
from pydiff_mpp.mpp_structure import _structural_signature

# ── Text normalization ───────────────────────────────────────


def normalize_text(text):
    """Normalize flattened body text for verification.

    Currently identity — placeholder for future text-level dont-cares.
    """
    return text


# ── EP normalization ─────────────────────────────────────────


def _normalize_params(tmpl):
    """Canonicalize parameter storage to tmpl_params dict format.

    Handles three historical formats:
      - tmpl_params dict  (current)
      - tmpl_args_dic dict (transitional)
      - tmpl_args list (oldest)
    """
    # Already in current format
    if "tmpl_params" in tmpl:
        return
    if "tmpl_args_dic" in tmpl:
        tmpl["tmpl_params"] = tmpl.pop("tmpl_args_dic")
        return
    args = tmpl.get("tmpl_args")
    if args is None:
        return
    params = {}
    positional_index = 1
    for arg in args:
        if isinstance(arg, str) and "=" in arg:
            key, value = arg.split("=", 1)
            params[key] = value
        elif (
            isinstance(arg, list) and arg and isinstance(arg[0], str) and "=" in arg[0]
        ):
            key, head = arg[0].split("=", 1)
            tail = arg[1:]
            if not head and len(tail) == 1:
                params[key] = tail[0]
            else:
                params[key] = ([head] if head else []) + tail
        else:
            params[str(positional_index)] = arg
            positional_index += 1
    tmpl["tmpl_params"] = params
    del tmpl["tmpl_args"]


def _normalize_qvk(tmpl):
    """Normalize קרי ולא כתיב to always have two params.

    Old one-arg form: param "1" = "[אִ֖ישׁ]"
    New two-arg form: param "1" = "[אִ֖ישׁ]", param "2" = "אִ֖ישׁ"

    Synthesize param "2" from param "1" by stripping square brackets.
    """
    if not _is_qere_velo_ketiv_template(tmpl["tmpl_name"]):
        return
    p2 = _get_param(tmpl, "2")
    if p2 is not _MISSING:
        return  # already two-arg
    p1 = _get_param(tmpl, "1")
    if p1 is _MISSING:
        return
    # Synthesize param 2
    flat = _flatten_element(p1)
    stripped = _strip_square_brackets(flat)
    if "tmpl_params" in tmpl:
        tmpl["tmpl_params"]["2"] = stripped
    elif "tmpl_args_dic" in tmpl:
        tmpl["tmpl_args_dic"]["2"] = stripped
    elif "tmpl_args" in tmpl:
        tmpl["tmpl_args"].append(stripped)


def _normalize_nusach_param2(tmpl):
    """Replace נוסח param 2 with a sentinel.

    Param 2 of נוסח templates contains manuscript-note text that is
    informational only.  Changes to it are not diff-description bugs.
    """
    if tmpl["tmpl_name"] != "נוסח":
        return
    for dict_key in ("tmpl_params", "tmpl_args_dic"):
        d = tmpl.get(dict_key)
        if d is not None and "2" in d:
            d["2"] = "DONT-CARE"
            return
    args = tmpl.get("tmpl_args")
    if args is not None and len(args) >= 2:
        args[1] = "DONT-CARE"


def _normalize_element(el):
    """Recursively normalize an EP element (in place on a deep copy)."""
    if isinstance(el, dict):
        if "tmpl_name" in el:
            _normalize_params(el)
            _normalize_qvk(el)
            _normalize_nusach_param2(el)
        for value in el.values():
            _normalize_element(value)
    elif isinstance(el, list):
        for item in el:
            _normalize_element(item)


def normalize_ep(ep):
    """Return a deep copy of *ep* with dont-care differences neutralized.

    Transformations applied:
    1. Parameter format canonicalized to tmpl_params
    2. קרי ולא כתיב normalized to two-arg form
    3. נוסח param 2 replaced with "DONT-CARE"
    """
    ep_copy = copy.deepcopy(ep)
    _normalize_element(ep_copy)
    return ep_copy


# ── Structural signature ─────────────────────────────────────


def normalize_structure(ep):
    """Return the structural signature of a normalized EP."""
    return _structural_signature(normalize_ep(ep))
